// CS·IT: 데이터베이스 / 네트워크 / 운영체제 / API·Web / Cloud / Git
import type { SeedQuestion } from "@/db/seed/seedTypes";

export const csitQuestions: SeedQuestion[] = [
  // ───────────── 데이터베이스 ─────────────
  {
    themeName: "데이터베이스",
    type: "def-to-term",
    tagNames: ["DB"],
    payload: { term: "PRIMARY KEY", definition: "테이블에서 각 행을 고유하게 식별하는 제약조건" },
  },
  {
    themeName: "데이터베이스",
    type: "multiple-choice",
    tagNames: ["DB"],
    explanation: "MongoDB는 문서 지향 NoSQL 데이터베이스로 관계형 데이터베이스(RDBMS)가 아니다.",
    payload: {
      prompt: "다음 중 RDBMS가 아닌 것은?",
      options: ["MySQL", "PostgreSQL", "MongoDB", "Oracle"],
      correctIndex: 2,
    },
  },
  {
    themeName: "데이터베이스",
    type: "term-to-def",
    tagNames: ["DB"],
    payload: { term: "정규화", definition: "데이터 중복을 줄이고 무결성을 높이기 위해 테이블을 구조화하는 과정" },
  },
  {
    themeName: "데이터베이스",
    type: "def-to-term",
    difficulty: "intermediate",
    tagNames: ["DB"],
    payload: { term: "NoSQL", definition: "고정된 테이블 스키마 없이 문서, 키-값 등 다양한 형태로 데이터를 저장하는 데이터베이스" },
  },
  {
    themeName: "데이터베이스",
    type: "multiple-choice",
    difficulty: "advanced",
    tagNames: ["DB"],
    explanation: "샤딩은 데이터를 여러 서버에 나눠 저장해 하나의 DB가 처리해야 할 부하를 분산시키는 기법이다.",
    payload: {
      prompt: "대량의 데이터를 여러 서버에 나누어 저장해 부하를 분산시키는 기법은?",
      options: ["샤딩", "정규화", "인덱싱", "트리거"],
      correctIndex: 0,
    },
  },
  {
    themeName: "데이터베이스",
    type: "def-to-term",
    difficulty: "advanced",
    tagNames: ["DB"],
    payload: { term: "복제(Replication)", definition: "동일한 데이터를 여러 서버에 복사해 가용성과 읽기 성능을 높이는 기법" },
  },
  {
    themeName: "데이터베이스",
    type: "term-to-def",
    difficulty: "advanced",
    tagNames: ["DB"],
    payload: { term: "트리거", definition: "특정 테이블에 삽입·수정·삭제가 일어날 때 자동으로 실행되도록 정의한 절차" },
  },
  {
    themeName: "데이터베이스",
    type: "essay",
    difficulty: "advanced",
    tagNames: ["DB"],
    payload: {
      prompt: "테이블에 인덱스를 많이 만들수록 조회는 빨라지지만 쓰기 성능이 나빠지는 이유를 한 문장으로 설명하시오.",
      answer: "데이터가 삽입·수정될 때마다 관련된 모든 인덱스도 함께 갱신해야 하기 때문이다.",
    },
  },
  {
    themeName: "데이터베이스",
    type: "def-to-term",
    difficulty: "advanced",
    tagNames: ["DB"],
    payload: { term: "낙관적 동시성 제어", definition: "충돌이 드물다고 가정하고 커밋 시점에만 검증하는 동시성 제어 방식" },
  },
  {
    themeName: "데이터베이스",
    type: "term-to-def",
    difficulty: "intermediate",
    tagNames: ["DB"],
    payload: { term: "외래키", definition: "다른 테이블의 기본키를 참조해 두 테이블 간 관계를 표현하는 컬럼" },
  },

  // ───────────── 네트워크 ─────────────
  {
    themeName: "네트워크",
    type: "def-to-term",
    tagNames: ["네트워크"],
    payload: { term: "TCP", definition: "데이터를 순서대로 신뢰성 있게 전달하는 연결 지향형 전송 프로토콜" },
  },
  {
    themeName: "네트워크",
    type: "term-to-def",
    tagNames: ["네트워크"],
    payload: { term: "DNS", definition: "도메인 이름을 IP 주소로 변환해주는 시스템" },
  },
  {
    themeName: "네트워크",
    type: "answer-input",
    tagNames: ["네트워크"],
    payload: { prompt: "HTTPS가 사용하는 기본 포트 번호는?", answer: "443" },
  },
  {
    themeName: "네트워크",
    type: "def-to-term",
    difficulty: "intermediate",
    tagNames: ["네트워크"],
    payload: { term: "UDP", definition: "연결 설정 없이 순서 보장이나 재전송 없이 빠르게 데이터를 전송하는 프로토콜" },
  },
  {
    themeName: "네트워크",
    type: "multiple-choice",
    difficulty: "intermediate",
    tagNames: ["네트워크"],
    explanation: "TCP는 신뢰성을, UDP는 속도를 우선하는 프로토콜이다.",
    payload: {
      prompt: "실시간 스트리밍처럼 속도가 중요하고 일부 손실을 허용할 수 있는 통신에 적합한 프로토콜은?",
      options: ["TCP", "UDP", "FTP", "SMTP"],
      correctIndex: 1,
    },
  },
  {
    themeName: "네트워크",
    type: "def-to-term",
    difficulty: "advanced",
    tagNames: ["네트워크"],
    payload: { term: "3-way handshake", definition: "TCP 연결을 맺기 위해 SYN, SYN-ACK, ACK를 주고받는 과정" },
  },
  {
    themeName: "네트워크",
    type: "term-to-def",
    difficulty: "advanced",
    tagNames: ["네트워크"],
    payload: { term: "NAT", definition: "사설 IP 주소를 공인 IP 주소로 변환해 여러 기기가 하나의 공인 IP를 공유하게 하는 기술" },
  },
  {
    themeName: "네트워크",
    type: "answer-input",
    difficulty: "beginner",
    tagNames: ["네트워크"],
    payload: { prompt: "일반 HTTP가 사용하는 기본 포트 번호는?", answer: "80" },
  },
  {
    themeName: "네트워크",
    type: "def-to-term",
    difficulty: "advanced",
    tagNames: ["네트워크"],
    payload: { term: "방화벽", definition: "미리 정한 규칙에 따라 네트워크로 들어오고 나가는 트래픽을 감시·차단하는 보안 장치" },
  },
  {
    themeName: "네트워크",
    type: "term-to-def",
    difficulty: "advanced",
    tagNames: ["네트워크"],
    payload: { term: "로드밸런싱", definition: "여러 서버에 요청을 고르게 분산시켜 특정 서버로 부하가 몰리지 않게 하는 기법" },
  },

  // ───────────── 운영체제 ─────────────
  {
    themeName: "운영체제",
    type: "term-to-def",
    tagNames: ["OS"],
    payload: { term: "데드락", definition: "두 개 이상의 프로세스가 서로 자원을 기다리며 무한히 대기하는 상태" },
  },
  {
    themeName: "운영체제",
    type: "def-to-term",
    tagNames: ["OS"],
    payload: { term: "컨텍스트 스위칭", definition: "CPU가 한 프로세스에서 다른 프로세스로 실행을 전환하는 과정" },
  },
  {
    themeName: "운영체제",
    type: "term-to-def",
    tagNames: ["OS"],
    payload: { term: "가상 메모리", definition: "물리 메모리보다 큰 주소 공간을 사용할 수 있게 하는 메모리 관리 기법" },
  },
  {
    themeName: "운영체제",
    type: "def-to-term",
    difficulty: "intermediate",
    tagNames: ["OS"],
    payload: { term: "프로세스", definition: "운영체제로부터 독립된 메모리 공간을 할당받아 실행 중인 프로그램" },
  },
  {
    themeName: "운영체제",
    type: "term-to-def",
    difficulty: "intermediate",
    tagNames: ["OS"],
    payload: { term: "스레드", definition: "프로세스 내에서 메모리 공간을 공유하며 독립적으로 실행되는 작업 단위" },
  },
  {
    themeName: "운영체제",
    type: "multiple-choice",
    difficulty: "intermediate",
    tagNames: ["OS"],
    explanation: "스레드는 같은 프로세스의 메모리를 공유해 프로세스 간 통신보다 데이터 공유가 가볍다.",
    payload: {
      prompt: "프로세스와 비교했을 때 스레드의 특징으로 옳은 것은?",
      options: ["별도의 메모리 공간을 갖는다", "같은 프로세스 내 메모리를 공유한다", "항상 하나만 존재한다", "운영체제가 생성하지 않는다"],
      correctIndex: 1,
    },
  },
  {
    themeName: "운영체제",
    type: "def-to-term",
    difficulty: "advanced",
    tagNames: ["OS"],
    payload: { term: "세마포어", definition: "여러 프로세스가 공유 자원에 접근하는 순서를 제어하는 동기화 도구" },
  },
  {
    themeName: "운영체제",
    type: "term-to-def",
    difficulty: "advanced",
    tagNames: ["OS"],
    payload: { term: "페이지 폴트", definition: "프로세스가 참조한 페이지가 물리 메모리에 없어 디스크에서 불러와야 하는 상황" },
  },
  {
    themeName: "운영체제",
    type: "def-to-term",
    difficulty: "intermediate",
    tagNames: ["OS"],
    payload: { term: "스케줄링", definition: "CPU를 어떤 프로세스에 얼마 동안 할당할지 결정하는 운영체제의 작업" },
  },
  {
    themeName: "운영체제",
    type: "multiple-choice",
    difficulty: "advanced",
    tagNames: ["OS"],
    explanation: "데드락이 발생하려면 상호배제, 점유대기, 비선점, 순환대기 네 조건이 모두 충족되어야 한다.",
    payload: {
      prompt: "데드락 발생 조건 중 '프로세스가 자원을 가진 채로 다른 자원을 기다리는' 조건의 이름은?",
      options: ["상호배제", "점유대기", "비선점", "순환대기"],
      correctIndex: 1,
    },
  },

  // ───────────── API·Web ─────────────
  {
    themeName: "API·Web",
    type: "def-to-term",
    tagNames: ["API"],
    payload: { term: "REST API", definition: "자원을 URI로 표현하고 HTTP 메서드로 행위를 정의하는 API 설계 방식" },
  },
  {
    themeName: "API·Web",
    type: "answer-input",
    tagNames: ["API"],
    payload: { prompt: "리소스를 새로 생성할 때 주로 사용하는 HTTP 메서드는?", answer: "POST" },
  },
  {
    themeName: "API·Web",
    type: "term-to-def",
    tagNames: ["API"],
    payload: { term: "CORS", definition: "다른 출처의 웹 페이지에서 리소스를 요청할 수 있도록 허용하는 브라우저 보안 정책" },
  },
  {
    themeName: "API·Web",
    type: "answer-input",
    difficulty: "intermediate",
    tagNames: ["API"],
    payload: { prompt: "리소스 전체를 완전히 교체할 때 쓰는 HTTP 메서드는? (PATCH와 구분)", answer: "PUT" },
  },
  {
    themeName: "API·Web",
    type: "def-to-term",
    difficulty: "intermediate",
    tagNames: ["API"],
    payload: { term: "상태 코드 404", definition: "요청한 리소스를 서버에서 찾을 수 없을 때 반환되는 HTTP 상태 코드" },
  },
  {
    themeName: "API·Web",
    type: "term-to-def",
    difficulty: "intermediate",
    tagNames: ["API"],
    payload: { term: "상태 코드 401", definition: "인증되지 않은 요청임을 나타내는 HTTP 상태 코드" },
  },
  {
    themeName: "API·Web",
    type: "multiple-choice",
    difficulty: "advanced",
    tagNames: ["API"],
    explanation: "GraphQL은 클라이언트가 필요한 필드만 지정해 원하는 데이터만 받을 수 있게 하는 쿼리 언어다.",
    payload: {
      prompt: "클라이언트가 필요한 필드를 직접 지정해 정확히 그 데이터만 받을 수 있는 API 방식은?",
      options: ["REST", "GraphQL", "SOAP", "WebSocket"],
      correctIndex: 1,
    },
  },
  {
    themeName: "API·Web",
    type: "def-to-term",
    difficulty: "advanced",
    tagNames: ["API"],
    payload: { term: "JWT", definition: "사용자 인증 정보를 서명된 토큰 형태로 담아 서버 간 주고받는 방식" },
  },
  {
    themeName: "API·Web",
    type: "term-to-def",
    difficulty: "advanced",
    tagNames: ["API"],
    payload: { term: "웹소켓", definition: "클라이언트와 서버가 연결을 유지한 채 양방향으로 실시간 데이터를 주고받는 통신 프로토콜" },
  },
  {
    themeName: "API·Web",
    type: "def-to-term",
    difficulty: "intermediate",
    tagNames: ["API"],
    payload: { term: "상태 코드 500", definition: "서버 내부에 예기치 못한 오류가 발생했음을 나타내는 HTTP 상태 코드" },
  },

  // ───────────── Cloud ─────────────
  {
    themeName: "Cloud",
    type: "term-to-def",
    tagNames: ["Cloud"],
    payload: { term: "오토스케일링", definition: "트래픽 변화에 따라 서버 인스턴스 수를 자동으로 늘리거나 줄이는 기능" },
  },
  {
    themeName: "Cloud",
    type: "def-to-term",
    tagNames: ["Cloud"],
    payload: { term: "IaaS", definition: "서버, 스토리지 등 인프라 자원을 가상화해 제공하는 클라우드 서비스 모델" },
  },
  {
    themeName: "Cloud",
    type: "term-to-def",
    tagNames: ["Cloud"],
    payload: { term: "로드밸런서", definition: "여러 서버에 트래픽을 분산시켜 부하를 고르게 나누는 장치" },
  },
  {
    themeName: "Cloud",
    type: "def-to-term",
    difficulty: "intermediate",
    tagNames: ["Cloud"],
    payload: { term: "PaaS", definition: "애플리케이션 실행에 필요한 운영체제와 미들웨어까지 관리해주는 클라우드 서비스 모델" },
  },
  {
    themeName: "Cloud",
    type: "term-to-def",
    difficulty: "advanced",
    tagNames: ["Cloud"],
    payload: { term: "컨테이너", definition: "애플리케이션과 실행에 필요한 라이브러리를 함께 패키징해 격리 실행하는 경량 가상화 기술" },
  },
  {
    themeName: "Cloud",
    type: "def-to-term",
    difficulty: "advanced",
    tagNames: ["Cloud"],
    payload: { term: "서버리스", definition: "서버 인프라 관리를 클라우드 제공자에게 맡기고 코드 실행 단위로만 비용을 지불하는 방식" },
  },
  {
    themeName: "Cloud",
    type: "term-to-def",
    difficulty: "advanced",
    tagNames: ["Cloud"],
    payload: { term: "SaaS", definition: "설치 없이 인터넷을 통해 완성된 소프트웨어를 그대로 사용하는 클라우드 서비스 모델" },
  },
  {
    themeName: "Cloud",
    type: "def-to-term",
    difficulty: "advanced",
    tagNames: ["Cloud"],
    payload: { term: "CDN", definition: "전 세계 여러 지역의 서버에 콘텐츠를 분산 저장해 사용자와 가까운 서버에서 빠르게 전달하는 네트워크" },
  },

  // ───────────── Git ─────────────
  {
    themeName: "Git",
    type: "blank",
    difficulty: "beginner",
    tagNames: ["Git"],
    explanation: "git commit -m 뒤에 커밋 메시지를 작성한다.",
    payload: { template: "git {{b1}} -m \"fix bug\"", blanks: [{ id: "b1", answer: "commit" }] },
  },
  {
    themeName: "Git",
    type: "def-to-term",
    tagNames: ["Git"],
    payload: { term: "브랜치", definition: "메인 코드에 영향을 주지 않고 독립적으로 작업할 수 있게 분기한 작업 흐름" },
  },
  {
    themeName: "Git",
    type: "term-to-def",
    tagNames: ["Git"],
    payload: { term: "머지 컨플릭트", definition: "두 브랜치에서 같은 부분을 다르게 수정해 자동 병합이 불가능한 상태" },
  },
  {
    themeName: "Git",
    type: "blank",
    difficulty: "beginner",
    tagNames: ["Git"],
    explanation: "git clone 뒤에 원격 저장소 주소를 지정해 로컬로 복제한다.",
    payload: { template: "git {{b1}} https://github.com/user/repo.git", blanks: [{ id: "b1", answer: "clone" }] },
  },
  {
    themeName: "Git",
    type: "def-to-term",
    difficulty: "intermediate",
    tagNames: ["Git"],
    payload: { term: "git pull", definition: "원격 저장소의 최신 변경 사항을 가져와 로컬 브랜치에 병합하는 명령" },
  },
  {
    themeName: "Git",
    type: "term-to-def",
    difficulty: "intermediate",
    tagNames: ["Git"],
    payload: { term: "git rebase", definition: "커밋들을 다른 기준 커밋 위로 옮겨 히스토리를 직선으로 재구성하는 명령" },
  },
  {
    themeName: "Git",
    type: "multiple-choice",
    difficulty: "intermediate",
    tagNames: ["Git"],
    explanation: "git status는 작업 디렉터리와 스테이징 영역의 변경 상태를 보여준다.",
    payload: {
      prompt: "현재 변경된 파일과 스테이징 상태를 확인할 때 사용하는 명령은?",
      options: ["git status", "git log", "git diff", "git show"],
      correctIndex: 0,
    },
  },
  {
    themeName: "Git",
    type: "def-to-term",
    difficulty: "advanced",
    tagNames: ["Git"],
    payload: { term: ".gitignore", definition: "버전 관리에서 제외할 파일이나 폴더 패턴을 지정하는 설정 파일" },
  },
  {
    themeName: "Git",
    type: "term-to-def",
    difficulty: "advanced",
    tagNames: ["Git"],
    payload: { term: "git stash", definition: "작업 중인 변경 사항을 커밋하지 않고 임시로 저장해두는 명령" },
  },
  {
    themeName: "Git",
    type: "def-to-term",
    difficulty: "intermediate",
    tagNames: ["Git"],
    payload: { term: "Pull Request", definition: "작업한 브랜치의 변경 사항을 리뷰받은 뒤 메인 브랜치에 병합해달라고 요청하는 절차" },
  },
];
