// 데이터: 데이터분석 / 통계 / Product Analytics / Business Analytics / A/B Test / 데이터 시각화
import type { SeedQuestion } from "@/db/seed/seedTypes";

export const dataQuestions: SeedQuestion[] = [
  // ───────────── 데이터분석 ─────────────
  {
    themeName: "데이터분석",
    type: "term-to-def",
    tagNames: ["데이터분석"],
    payload: { term: "결측치", definition: "데이터셋에서 값이 누락되어 비어 있는 항목" },
  },
  {
    themeName: "데이터분석",
    type: "def-to-term",
    tagNames: ["데이터분석"],
    payload: { term: "이상치", definition: "다른 관측값과 비교했을 때 비정상적으로 크거나 작은 값" },
  },
  {
    themeName: "데이터분석",
    type: "multiple-choice",
    tagNames: ["데이터분석"],
    explanation: "정규화는 스케일을 조정하는 전처리 기법이지 결측치 처리 방법이 아니다.",
    payload: {
      prompt: "결측치 처리 방법이 아닌 것은?",
      options: ["평균 대체", "삭제", "정규화", "보간법"],
      correctIndex: 2,
    },
  },
  {
    themeName: "데이터분석",
    type: "def-to-term",
    difficulty: "intermediate",
    tagNames: ["데이터분석"],
    payload: { term: "정규화(Normalization)", definition: "서로 다른 범위를 가진 변수를 0~1 등 동일한 척도로 맞추는 전처리 기법" },
  },
  {
    themeName: "데이터분석",
    type: "term-to-def",
    difficulty: "intermediate",
    tagNames: ["데이터분석"],
    payload: { term: "표준화(Standardization)", definition: "변수의 평균을 0, 표준편차를 1로 맞추는 스케일 조정 기법" },
  },
  {
    themeName: "데이터분석",
    type: "multiple-choice",
    difficulty: "intermediate",
    tagNames: ["데이터분석"],
    explanation: "원-핫 인코딩은 범주형 변수를 0/1 벡터로 변환해 모델이 처리할 수 있게 한다.",
    payload: {
      prompt: "범주형 변수를 여러 개의 0/1 컬럼으로 변환하는 인코딩 방식은?",
      options: ["라벨 인코딩", "원-핫 인코딩", "표준화", "정규화"],
      correctIndex: 1,
    },
  },
  {
    themeName: "데이터분석",
    type: "def-to-term",
    difficulty: "intermediate",
    tagNames: ["데이터분석"],
    payload: { term: "라벨 인코딩", definition: "범주형 값을 0, 1, 2 같은 정수로 하나씩 매핑하는 인코딩 방식" },
  },
  {
    themeName: "데이터분석",
    type: "term-to-def",
    tagNames: ["데이터분석"],
    payload: { term: "피처 엔지니어링", definition: "원본 데이터로부터 모델 성능에 도움이 되는 새로운 변수를 만들어내는 작업" },
  },
  {
    themeName: "데이터분석",
    type: "multiple-choice",
    difficulty: "intermediate",
    tagNames: ["데이터분석"],
    explanation: "IQR(사분위 범위)을 벗어나는 값을 이상치로 판단하는 방법이 널리 쓰인다.",
    payload: {
      prompt: "박스플롯에서 이상치를 판단할 때 주로 사용하는 기준은?",
      options: ["평균과 표준편차", "IQR(사분위 범위)", "최댓값과 최솟값", "중앙값만"],
      correctIndex: 1,
    },
  },
  {
    themeName: "데이터분석",
    type: "def-to-term",
    difficulty: "advanced",
    tagNames: ["데이터분석"],
    payload: { term: "다중공선성", definition: "독립변수들 간 상관관계가 높아 회귀 분석 결과 해석이 불안정해지는 문제" },
  },
  {
    themeName: "데이터분석",
    type: "term-to-def",
    difficulty: "advanced",
    tagNames: ["데이터분석"],
    payload: { term: "EDA", definition: "본격적인 모델링 전에 데이터의 구조와 패턴을 파악하는 탐색적 데이터 분석" },
  },
  {
    themeName: "데이터분석",
    type: "essay",
    difficulty: "intermediate",
    tagNames: ["데이터분석"],
    payload: {
      prompt: "결측치를 평균으로 대체할 때의 단점을 한 문장으로 설명하시오.",
      answer: "데이터의 분산이 줄어들고 변수 간 상관관계가 왜곡될 수 있다.",
    },
  },
  {
    themeName: "데이터분석",
    type: "def-to-term",
    difficulty: "intermediate",
    tagNames: ["데이터분석"],
    payload: { term: "데이터 클렌징", definition: "중복, 오류, 형식 불일치 등을 찾아 정제하는 데이터 전처리 작업" },
  },
  {
    themeName: "데이터분석",
    type: "term-to-def",
    difficulty: "intermediate",
    tagNames: ["데이터분석"],
    payload: { term: "롱 포맷", definition: "각 관측값이 한 행에 하나씩 세로로 쌓인 데이터 형태" },
  },
  {
    themeName: "데이터분석",
    type: "def-to-term",
    difficulty: "intermediate",
    tagNames: ["데이터분석"],
    payload: { term: "와이드 포맷", definition: "각 변수가 별도의 열로 펼쳐져 있는 데이터 형태" },
  },
  {
    themeName: "데이터분석",
    type: "multiple-choice",
    difficulty: "advanced",
    tagNames: ["데이터분석"],
    explanation: "생존자 편향은 실패하거나 탈락한 사례가 제외돼 분석 결과가 왜곡되는 대표적인 표본 편향이다.",
    payload: {
      prompt: "실패해 사라진 사례는 제외하고 살아남은 사례만 분석해 결론이 왜곡되는 현상은?",
      options: ["다중공선성", "생존자 편향", "과적합", "차원의 저주"],
      correctIndex: 1,
    },
  },
  {
    themeName: "데이터분석",
    type: "def-to-term",
    difficulty: "advanced",
    tagNames: ["데이터분석"],
    payload: { term: "차원의 저주", definition: "변수(차원) 수가 늘어날수록 데이터가 공간에 희박해져 분석이 어려워지는 현상" },
  },
  {
    themeName: "데이터분석",
    type: "term-to-def",
    difficulty: "advanced",
    tagNames: ["데이터분석"],
    payload: { term: "샘플링 편향", definition: "표본이 전체 모집단을 대표하지 못해 분석 결과가 한쪽으로 치우치는 문제" },
  },
  {
    themeName: "데이터분석",
    type: "answer-input",
    difficulty: "beginner",
    tagNames: ["데이터분석"],
    payload: { prompt: "데이터 1, 2, 3, 4, 5의 분산을 구할 때 가장 먼저 계산해야 하는 값은? (한 단어)", answer: "평균" },
  },
  {
    themeName: "데이터분석",
    type: "def-to-term",
    difficulty: "advanced",
    tagNames: ["데이터분석"],
    payload: { term: "타겟 누수", definition: "예측에 실제로 사용할 수 없는 미래 정보가 학습 데이터에 섞여 모델 성능이 비정상적으로 좋아 보이는 문제" },
  },

  // ───────────── 통계 ─────────────
  {
    themeName: "통계",
    type: "term-to-def",
    tagNames: ["통계"],
    payload: { term: "표준편차", definition: "데이터가 평균으로부터 흩어진 정도를 나타내는 값" },
  },
  {
    themeName: "통계",
    type: "def-to-term",
    tagNames: ["통계"],
    payload: { term: "p-값", definition: "귀무가설이 참일 때 관측된 결과 이상이 나올 확률" },
  },
  {
    themeName: "통계",
    type: "answer-input",
    tagNames: ["통계"],
    payload: { prompt: "유의수준을 흔히 알파(α)라고 부른다. 일반적으로 많이 쓰이는 값은? (소수로 답)", answer: "0.05" },
  },
  {
    themeName: "통계",
    type: "term-to-def",
    difficulty: "intermediate",
    tagNames: ["통계"],
    payload: { term: "제1종 오류", definition: "실제로는 참인 귀무가설을 잘못 기각하는 오류" },
  },
  {
    themeName: "통계",
    type: "def-to-term",
    difficulty: "intermediate",
    tagNames: ["통계"],
    payload: { term: "제2종 오류", definition: "실제로는 거짓인 귀무가설을 잘못 채택(기각하지 못함)하는 오류" },
  },
  {
    themeName: "통계",
    type: "term-to-def",
    difficulty: "intermediate",
    tagNames: ["통계"],
    payload: { term: "중심극한정리", definition: "표본 크기가 커질수록 표본평균의 분포가 정규분포에 가까워진다는 정리" },
  },
  {
    themeName: "통계",
    type: "multiple-choice",
    difficulty: "beginner",
    tagNames: ["통계"],
    explanation: "이상치가 있으면 평균이 크게 흔들리지만 중앙값은 상대적으로 안정적이다.",
    payload: {
      prompt: "극단적인 이상치가 있는 데이터의 중심 경향을 볼 때 평균보다 안정적인 지표는?",
      options: ["분산", "중앙값", "표준편차", "범위"],
      correctIndex: 1,
    },
  },
  {
    themeName: "통계",
    type: "def-to-term",
    difficulty: "intermediate",
    tagNames: ["통계"],
    payload: { term: "상관계수", definition: "두 변수 간 선형 관계의 강도와 방향을 -1~1 사이 값으로 나타낸 지표" },
  },
  {
    themeName: "통계",
    type: "essay",
    difficulty: "intermediate",
    tagNames: ["통계"],
    payload: {
      prompt: "상관관계와 인과관계의 차이를 한 문장으로 설명하시오.",
      answer: "상관관계는 두 변수가 함께 변하는 경향을 보이는 것이고, 인과관계는 한 변수가 다른 변수의 변화를 실제로 일으키는 것이다.",
    },
  },
  {
    themeName: "통계",
    type: "term-to-def",
    difficulty: "advanced",
    tagNames: ["통계"],
    payload: { term: "신뢰구간", definition: "모수가 특정 확률로 포함될 것으로 추정되는 값의 범위" },
  },
  {
    themeName: "통계",
    type: "def-to-term",
    difficulty: "advanced",
    tagNames: ["통계"],
    payload: { term: "t-검정", definition: "표본 크기가 작거나 모분산을 모를 때 두 집단의 평균 차이를 검정하는 방법" },
  },
  {
    themeName: "통계",
    type: "def-to-term",
    difficulty: "advanced",
    tagNames: ["통계"],
    payload: { term: "카이제곱 검정", definition: "범주형 변수 간 독립성 또는 적합도를 검정하는 통계 방법" },
  },
  {
    themeName: "통계",
    type: "multiple-choice",
    difficulty: "intermediate",
    tagNames: ["통계"],
    explanation: "정규분포는 평균을 중심으로 좌우 대칭인 종 모양 분포다.",
    payload: {
      prompt: "평균을 중심으로 좌우 대칭인 종 모양의 확률분포는?",
      options: ["이항분포", "정규분포", "포아송분포", "균등분포"],
      correctIndex: 1,
    },
  },
  {
    themeName: "통계",
    type: "term-to-def",
    difficulty: "advanced",
    tagNames: ["통계"],
    payload: { term: "왜도", definition: "분포가 좌우 대칭에서 벗어나 한쪽으로 치우친 정도를 나타내는 값" },
  },
  {
    themeName: "통계",
    type: "answer-input",
    difficulty: "beginner",
    tagNames: ["통계"],
    payload: { prompt: "1, 2, 3, 4, 100 다섯 개 값의 중앙값은?", answer: "3" },
  },
  {
    themeName: "통계",
    type: "def-to-term",
    difficulty: "beginner",
    tagNames: ["통계"],
    payload: { term: "최빈값", definition: "데이터에서 가장 자주 나타나는 값" },
  },
  {
    themeName: "통계",
    type: "term-to-def",
    difficulty: "intermediate",
    tagNames: ["통계"],
    payload: { term: "분산", definition: "각 데이터가 평균으로부터 떨어진 정도를 제곱해 평균 낸 값" },
  },
  {
    themeName: "통계",
    type: "multiple-choice",
    difficulty: "intermediate",
    tagNames: ["통계"],
    explanation: "표준편차는 분산에 제곱근을 씌워 원래 데이터와 같은 단위로 해석할 수 있게 만든 값이다.",
    payload: {
      prompt: "분산에 제곱근을 씌워 원래 데이터와 같은 단위로 만든 값은?",
      options: ["평균", "표준편차", "중앙값", "왜도"],
      correctIndex: 1,
    },
  },
  {
    themeName: "통계",
    type: "def-to-term",
    difficulty: "advanced",
    tagNames: ["통계"],
    payload: { term: "모집단", definition: "연구자가 알고 싶어 하는 대상 전체 집합" },
  },
  {
    themeName: "통계",
    type: "term-to-def",
    difficulty: "advanced",
    tagNames: ["통계"],
    payload: { term: "표본", definition: "모집단 전체를 조사하기 어려울 때 그 일부를 뽑아낸 부분집합" },
  },
  {
    themeName: "통계",
    type: "def-to-term",
    difficulty: "advanced",
    tagNames: ["통계"],
    payload: { term: "대립가설", definition: "귀무가설이 기각될 경우 채택되는, 연구자가 실제로 입증하고자 하는 가설" },
  },
  {
    themeName: "통계",
    type: "essay",
    difficulty: "advanced",
    tagNames: ["통계"],
    payload: {
      prompt: "p-값이 0.03일 때 유의수준 0.05 기준으로 어떤 결론을 내리는지 한 문장으로 설명하시오.",
      answer: "p-값이 유의수준보다 작으므로 귀무가설을 기각하고 통계적으로 유의미한 차이가 있다고 판단한다.",
    },
  },
  {
    themeName: "통계",
    type: "def-to-term",
    difficulty: "advanced",
    tagNames: ["통계"],
    payload: { term: "ANOVA", definition: "세 개 이상 집단의 평균 차이를 동시에 검정하는 분산분석 방법" },
  },
  {
    themeName: "통계",
    type: "term-to-def",
    difficulty: "advanced",
    tagNames: ["통계"],
    payload: { term: "회귀분석", definition: "독립변수와 종속변수 사이의 관계를 하나의 함수식으로 모델링하는 통계 기법" },
  },
  {
    themeName: "통계",
    type: "multiple-choice",
    difficulty: "advanced",
    tagNames: ["통계"],
    explanation: "결정계수(R²)는 회귀모델이 종속변수의 분산을 얼마나 설명하는지를 0~1 사이 값으로 나타낸다.",
    payload: {
      prompt: "회귀모델이 종속변수의 변동을 얼마나 잘 설명하는지 나타내는 0~1 사이 지표는?",
      options: ["p-값", "결정계수(R²)", "표준오차", "신뢰구간"],
      correctIndex: 1,
    },
  },
  {
    themeName: "통계",
    type: "def-to-term",
    difficulty: "advanced",
    tagNames: ["통계"],
    payload: { term: "표본추출", definition: "모집단에서 표본을 선택하는 절차나 방법" },
  },
  {
    themeName: "통계",
    type: "term-to-def",
    difficulty: "intermediate",
    tagNames: ["통계"],
    payload: { term: "범위", definition: "데이터의 최댓값에서 최솟값을 뺀, 데이터가 퍼진 폭을 나타내는 값" },
  },
  {
    themeName: "통계",
    type: "answer-input",
    difficulty: "beginner",
    tagNames: ["통계"],
    payload: { prompt: "정규분포에서 데이터가 좌우 어느 쪽으로도 치우치지 않았을 때 왜도 값은 대략 얼마인가?", answer: "0" },
  },
  {
    themeName: "통계",
    type: "def-to-term",
    difficulty: "advanced",
    tagNames: ["통계"],
    payload: { term: "포아송분포", definition: "정해진 시간이나 공간 안에서 어떤 사건이 발생하는 횟수를 모델링하는 이산확률분포" },
  },

  // ───────────── Product Analytics ─────────────
  {
    themeName: "Product Analytics",
    type: "term-to-def",
    tagNames: ["PA"],
    payload: { term: "리텐션", definition: "일정 기간 후에도 서비스를 계속 이용하는 사용자의 비율" },
  },
  {
    themeName: "Product Analytics",
    type: "def-to-term",
    tagNames: ["PA"],
    payload: { term: "퍼널", definition: "사용자가 서비스 유입부터 전환까지 거치는 단계별 흐름" },
  },
  {
    themeName: "Product Analytics",
    type: "term-to-def",
    tagNames: ["PA"],
    payload: { term: "코호트 분석", definition: "공통 특성을 가진 사용자 집단을 시간 흐름에 따라 추적 비교하는 분석" },
  },
  {
    themeName: "Product Analytics",
    type: "def-to-term",
    difficulty: "intermediate",
    tagNames: ["PA"],
    payload: { term: "이탈률(Churn Rate)", definition: "일정 기간 동안 서비스 이용을 중단한 고객의 비율" },
  },
  {
    themeName: "Product Analytics",
    type: "multiple-choice",
    difficulty: "intermediate",
    tagNames: ["PA"],
    explanation: "북극성 지표는 회사 전체가 추적하는 단 하나의 핵심 성장 지표를 뜻한다.",
    payload: {
      prompt: "제품 전체 성공을 대표하는 단 하나의 핵심 지표를 부르는 이름은?",
      options: ["KPI", "OKR", "북극성 지표", "ROAS"],
      correctIndex: 2,
    },
  },
  {
    themeName: "Product Analytics",
    type: "term-to-def",
    difficulty: "intermediate",
    tagNames: ["PA"],
    payload: { term: "액티베이션", definition: "신규 사용자가 제품의 핵심 가치를 처음 경험하는 시점의 행동 지표" },
  },
  {
    themeName: "Product Analytics",
    type: "def-to-term",
    difficulty: "intermediate",
    tagNames: ["PA"],
    payload: { term: "AARRR", definition: "획득-활성화-리텐션-추천-매출 단계로 사용자 여정을 분석하는 프레임워크" },
  },
  {
    themeName: "Product Analytics",
    type: "term-to-def",
    difficulty: "advanced",
    tagNames: ["PA"],
    payload: { term: "PMF", definition: "제품이 시장의 수요를 충분히 만족시키는 상태(Product-Market Fit)" },
  },
  {
    themeName: "Product Analytics",
    type: "essay",
    difficulty: "intermediate",
    tagNames: ["PA"],
    payload: {
      prompt: "DAU가 늘었는데 리텐션이 떨어지는 상황이 왜 위험 신호일 수 있는지 한 문장으로 설명하시오.",
      answer: "신규 유입은 늘지만 기존 사용자가 이탈하고 있다는 뜻이라 장기적으로는 성장이 지속되기 어렵다.",
    },
  },
  {
    themeName: "Product Analytics",
    type: "def-to-term",
    difficulty: "advanced",
    tagNames: ["PA"],
    payload: { term: "세그먼트", definition: "공통된 특성이나 행동을 기준으로 사용자를 나눈 집단" },
  },
  {
    themeName: "Product Analytics",
    type: "term-to-def",
    difficulty: "intermediate",
    tagNames: ["PA"],
    payload: { term: "WAU", definition: "일주일 동안 서비스를 이용한 순수 이용자 수" },
  },
  {
    themeName: "Product Analytics",
    type: "def-to-term",
    difficulty: "intermediate",
    tagNames: ["PA"],
    payload: { term: "온보딩", definition: "신규 사용자가 제품 사용법을 익히고 핵심 가치를 경험하도록 안내하는 초기 경험 설계" },
  },
  {
    themeName: "Product Analytics",
    type: "multiple-choice",
    difficulty: "intermediate",
    tagNames: ["PA"],
    explanation: "핵심 액션은 사용자가 해당 서비스의 가치를 실제로 체감하는 결정적 행동을 뜻한다.",
    payload: {
      prompt: "사진 공유 앱에서 '핵심 액션(Aha moment)'에 가장 가까운 행동은?",
      options: ["앱 다운로드", "회원가입 완료", "친구와 사진을 처음 공유", "설정 화면 열람"],
      correctIndex: 2,
    },
  },
  {
    themeName: "Product Analytics",
    type: "def-to-term",
    difficulty: "advanced",
    tagNames: ["PA"],
    payload: { term: "이벤트 트래킹", definition: "클릭, 조회 등 사용자의 개별 행동을 데이터로 기록하는 작업" },
  },
  {
    themeName: "Product Analytics",
    type: "term-to-def",
    difficulty: "advanced",
    tagNames: ["PA"],
    payload: { term: "A/A 테스트", definition: "동일한 두 그룹을 비교해 실험 도구 자체의 오류나 편향이 없는지 검증하는 테스트" },
  },
  {
    themeName: "Product Analytics",
    type: "def-to-term",
    difficulty: "advanced",
    tagNames: ["PA"],
    payload: { term: "스티키니스", definition: "사용자가 얼마나 자주, 습관적으로 서비스를 재방문하는지를 나타내는 정도" },
  },
  {
    themeName: "Product Analytics",
    type: "essay",
    difficulty: "advanced",
    tagNames: ["PA"],
    payload: {
      prompt: "리텐션 곡선이 특정 시점 이후 평평해지며 안정되는 것이 왜 긍정적인 신호인지 한 문장으로 설명하시오.",
      answer: "일정 수준의 사용자가 이탈하지 않고 꾸준히 남는다는 뜻이라 핵심 사용자층이 형성되었다고 볼 수 있기 때문이다.",
    },
  },
  {
    themeName: "Product Analytics",
    type: "def-to-term",
    difficulty: "advanced",
    tagNames: ["PA"],
    payload: { term: "동시 통계 오류", definition: "여러 지표를 동시에 반복 검정할 때 우연히 유의미해 보이는 결과가 늘어나는 문제" },
  },
  {
    themeName: "Product Analytics",
    type: "term-to-def",
    difficulty: "intermediate",
    tagNames: ["PA"],
    payload: { term: "인게이지먼트", definition: "사용자가 서비스 내에서 얼마나 적극적으로 상호작용하는지를 나타내는 정도" },
  },

  // ───────────── Business Analytics ─────────────
  {
    themeName: "Business Analytics",
    type: "def-to-term",
    tagNames: ["BA"],
    payload: { term: "LTV", definition: "고객 한 명이 서비스 이용 기간 동안 창출하는 총 매출 가치" },
  },
  {
    themeName: "Business Analytics",
    type: "term-to-def",
    tagNames: ["BA"],
    payload: { term: "CAC", definition: "고객 한 명을 신규로 획득하는 데 드는 평균 비용" },
  },
  {
    themeName: "Business Analytics",
    type: "answer-input",
    tagNames: ["BA"],
    payload: { prompt: "LTV가 CAC보다 커야 사업이 지속 가능하다. 이 비율을 나타내는 지표명은? (약어로 답)", answer: "LTV/CAC" },
  },
  {
    themeName: "Business Analytics",
    type: "def-to-term",
    difficulty: "intermediate",
    tagNames: ["BA"],
    payload: { term: "매출총이익률", definition: "매출에서 매출원가를 뺀 매출총이익이 매출에서 차지하는 비율" },
  },
  {
    themeName: "Business Analytics",
    type: "multiple-choice",
    difficulty: "intermediate",
    tagNames: ["BA"],
    explanation: "손익분기점은 매출과 총비용이 일치해 이익이 0이 되는 지점이다.",
    payload: {
      prompt: "매출과 총비용이 같아져 이익이 0이 되는 지점을 부르는 용어는?",
      options: ["손익분기점", "잉여현금흐름", "영업이익률", "재고회전율"],
      correctIndex: 0,
    },
  },
  {
    themeName: "Business Analytics",
    type: "term-to-def",
    difficulty: "advanced",
    tagNames: ["BA"],
    payload: { term: "재고회전율", definition: "일정 기간 동안 재고가 판매되어 순환한 횟수를 나타내는 지표" },
  },
  {
    themeName: "Business Analytics",
    type: "def-to-term",
    difficulty: "intermediate",
    tagNames: ["BA"],
    payload: { term: "영업이익률", definition: "매출에서 영업이익이 차지하는 비율" },
  },
  {
    themeName: "Business Analytics",
    type: "multiple-choice",
    difficulty: "intermediate",
    tagNames: ["BA"],
    explanation: "매출원가와 판매관리비를 모두 뺀 이익이 영업이익이다.",
    payload: {
      prompt: "매출에서 매출원가와 판매관리비를 모두 제외하고 남은 이익은?",
      options: ["매출총이익", "영업이익", "당기순이익", "잉여현금흐름"],
      correctIndex: 1,
    },
  },
  {
    themeName: "Business Analytics",
    type: "def-to-term",
    difficulty: "advanced",
    tagNames: ["BA"],
    payload: { term: "현금흐름", definition: "일정 기간 동안 기업에 들어오고 나간 현금의 흐름" },
  },
  {
    themeName: "Business Analytics",
    type: "essay",
    difficulty: "advanced",
    tagNames: ["BA"],
    payload: {
      prompt: "흑자 도산이 가능한 이유를 한 문장으로 설명하시오.",
      answer: "장부상 이익이 나더라도 매출채권 회수 지연 등으로 실제 현금이 부족하면 당장의 채무를 갚지 못해 도산할 수 있기 때문이다.",
    },
  },

  // ───────────── A/B Test ─────────────
  {
    themeName: "A/B Test",
    type: "term-to-def",
    tagNames: ["AB테스트"],
    payload: { term: "귀무가설", definition: "두 그룹 간 차이가 없다고 가정하는 통계적 기본 가설" },
  },
  {
    themeName: "A/B Test",
    type: "def-to-term",
    tagNames: ["AB테스트"],
    payload: { term: "통계적 유의성", definition: "관측된 차이가 우연이 아니라 실제 효과일 가능성이 충분히 높다는 것" },
  },
  {
    themeName: "A/B Test",
    type: "multiple-choice",
    tagNames: ["AB테스트"],
    explanation: "무작위 배정을 해야 두 그룹 간 다른 변수의 영향을 배제하고 처치 효과만 비교할 수 있다.",
    payload: {
      prompt: "A/B 테스트에서 실험군과 대조군을 나눌 때 가장 중요한 원칙은?",
      options: ["표본 크기를 다르게 한다", "무작위 배정한다", "매출 높은 유저만 넣는다", "테스트 기간을 짧게 한다"],
      correctIndex: 1,
    },
  },
  {
    themeName: "A/B Test",
    type: "term-to-def",
    difficulty: "intermediate",
    tagNames: ["AB테스트"],
    payload: { term: "샘플 사이즈", definition: "통계적으로 유의미한 결과를 얻기 위해 필요한 최소 표본 수" },
  },
  {
    themeName: "A/B Test",
    type: "def-to-term",
    difficulty: "advanced",
    tagNames: ["AB테스트"],
    payload: { term: "신규성 효과", definition: "새로운 변화 자체에 대한 호기심으로 일시적으로 지표가 개선되어 보이는 현상" },
  },
  {
    themeName: "A/B Test",
    type: "essay",
    difficulty: "advanced",
    tagNames: ["AB테스트"],
    payload: {
      prompt: "A/B 테스트를 통계적 유의성이 나오자마자 바로 중단하면 안 되는 이유를 한 문장으로 설명하시오.",
      answer: "충분한 표본과 기간이 쌓이기 전에 중단하면 우연에 의한 차이를 실제 효과로 잘못 판단할 위험이 커진다.",
    },
  },
  {
    themeName: "A/B Test",
    type: "def-to-term",
    difficulty: "intermediate",
    tagNames: ["AB테스트"],
    payload: { term: "실험군", definition: "A/B 테스트에서 새로운 변화를 적용받는 그룹" },
  },
  {
    themeName: "A/B Test",
    type: "term-to-def",
    difficulty: "intermediate",
    tagNames: ["AB테스트"],
    payload: { term: "대조군", definition: "A/B 테스트에서 기존 상태를 그대로 유지하는 비교 기준 그룹" },
  },
  {
    themeName: "A/B Test",
    type: "multiple-choice",
    difficulty: "advanced",
    tagNames: ["AB테스트"],
    explanation: "네트워크 효과가 있는 서비스는 실험군과 대조군이 서로 영향을 주고받아 순수한 효과 측정이 어려워진다.",
    payload: {
      prompt: "친구 추천 기능처럼 사용자 간 상호작용이 큰 기능을 A/B 테스트할 때 주의해야 할 점은?",
      options: [
        "표본이 항상 부족하다",
        "실험군과 대조군이 서로 영향을 줄 수 있다",
        "유의수준을 낮춰야 한다",
        "테스트가 불가능하다",
      ],
      correctIndex: 1,
    },
  },
  {
    themeName: "A/B Test",
    type: "def-to-term",
    difficulty: "advanced",
    tagNames: ["AB테스트"],
    payload: { term: "검정력", definition: "실제로 효과가 있을 때 그 효과를 통계적으로 올바르게 감지해낼 확률" },
  },

  // ───────────── 데이터 시각화 ─────────────
  {
    themeName: "데이터 시각화",
    type: "term-to-def",
    tagNames: ["시각화"],
    payload: { term: "히스토그램", definition: "연속형 데이터의 구간별 빈도를 막대로 나타낸 그래프" },
  },
  {
    themeName: "데이터 시각화",
    type: "def-to-term",
    tagNames: ["시각화"],
    payload: { term: "박스플롯", definition: "사분위수와 이상치를 함께 보여주는 데이터 분포 시각화 방법" },
  },
  {
    themeName: "데이터 시각화",
    type: "multiple-choice",
    tagNames: ["시각화"],
    explanation: "산점도는 두 연속형 변수 간 관계와 경향성을 파악하기에 적합하다.",
    payload: {
      prompt: "두 변수 간 상관관계를 보기에 가장 적합한 그래프는?",
      options: ["파이 차트", "산점도", "막대 그래프", "히스토그램"],
      correctIndex: 1,
    },
  },
  {
    themeName: "데이터 시각화",
    type: "def-to-term",
    difficulty: "intermediate",
    tagNames: ["시각화"],
    payload: { term: "히트맵", definition: "값의 크기를 색상 농도로 표현해 행렬 형태 데이터를 한눈에 보여주는 시각화" },
  },
  {
    themeName: "데이터 시각화",
    type: "essay",
    difficulty: "intermediate",
    tagNames: ["시각화"],
    payload: {
      prompt: "범주가 많은 데이터를 파이 차트로 표현하면 안 좋은 이유를 한 문장으로 설명하시오.",
      answer: "조각이 많아질수록 각 조각의 크기 차이를 눈으로 비교하기 어려워져 정보 전달력이 떨어진다.",
    },
  },
  {
    themeName: "데이터 시각화",
    type: "def-to-term",
    difficulty: "intermediate",
    tagNames: ["시각화"],
    payload: { term: "라인 차트", definition: "시간에 따른 값의 변화 추이를 선으로 이어 보여주는 그래프" },
  },
  {
    themeName: "데이터 시각화",
    type: "multiple-choice",
    difficulty: "intermediate",
    tagNames: ["시각화"],
    explanation: "막대 그래프는 범주별 값의 크기를 비교하는 데 가장 직관적이다.",
    payload: {
      prompt: "서로 다른 카테고리 간 수치 크기를 비교하기에 가장 직관적인 그래프는?",
      options: ["막대 그래프", "산점도", "선 그래프", "히트맵"],
      correctIndex: 0,
    },
  },
  {
    themeName: "데이터 시각화",
    type: "def-to-term",
    difficulty: "advanced",
    tagNames: ["시각화"],
    payload: { term: "대시보드", definition: "여러 지표와 시각화를 한 화면에 모아 현황을 한눈에 파악할 수 있게 만든 화면" },
  },
];
