// Python/Pandas 확장: 실행 결과 예측과 실무 코드 판단 위주.
// 출력 예측 문제의 정답은 파이썬 print 결과(repr)와 정확히 같은 문자열이다.
import { themed } from "@/db/seed/defaultQuestions/builders";

const q = themed("Python", ["Python"]);

export const pythonExtraQuestions = [
  // ── 실행 결과 예측: 기본 동작 ──
  q.input({
    id: "py-0050",
    d: "beginner",
    tags: ["참조"],
    why: "b = a는 리스트를 복사하지 않고 같은 객체를 가리키게 한다. b를 수정하면 a도 바뀐다.",
    q: "a = [1, 2]\nb = a\nb.append(3)\nprint(a)\n의 출력 결과는?",
    a: "[1, 2, 3]",
  }),
  q.input({
    id: "py-0051",
    d: "advanced",
    tags: ["함수"],
    why: "기본값 []는 함수 정의 시 한 번만 만들어져 호출 간에 공유된다. 기본값은 None으로 두고 함수 안에서 새 리스트를 만들어야 한다.",
    q: "def f(x, acc=[]):\n    acc.append(x)\n    return acc\nf(1)\nprint(f(2))\n의 출력 결과는?",
    a: "[1, 2]",
  }),
  q.input({
    id: "py-0052",
    d: "intermediate",
    tags: ["부동소수점"],
    why: "0.1과 0.2는 이진수로 정확히 표현되지 않아 합이 0.30000000000000004가 된다. 실수 비교는 math.isclose를 쓴다.",
    q: "print(0.1 + 0.2 == 0.3) 의 출력 결과는?",
    a: "False",
  }),
  q.input({
    id: "py-0053",
    d: "beginner",
    tags: ["truthiness"],
    why: "빈 리스트·빈 문자열·0·None은 거짓으로 평가된다. if items: 로 비어 있는지 검사할 수 있다.",
    q: "print(bool([])) 의 출력 결과는?",
    a: "False",
  }),
  q.input({
    id: "py-0054",
    d: "beginner",
    tags: ["문자열"],
    why: "문자열에 정수를 곱하면 그 횟수만큼 반복해 33이 된다. 숫자 곱셈(6)이 아니다.",
    q: "print(\"3\" * 2) 의 출력 결과는?",
    a: "33",
  }),
  q.input({
    id: "py-0055",
    d: "beginner",
    tags: ["슬라이싱"],
    why: "[::2]는 처음부터 끝까지 2칸 간격으로 원소를 뽑는다.",
    q: "print([1, 2, 3, 4, 5][::2]) 의 출력 결과는?",
    a: "[1, 3, 5]",
  }),
  q.input({
    id: "py-0056",
    d: "intermediate",
    tags: ["내장함수"],
    why: "zip은 가장 짧은 반복 가능 객체 길이에 맞춰 멈춘다. \"ab\"가 2글자라 2쌍만 생긴다.",
    q: "print(list(zip([1, 2, 3], \"ab\"))) 의 출력 결과는?",
    a: "[(1, 'a'), (2, 'b')]",
  }),
  q.input({
    id: "py-0057",
    d: "intermediate",
    tags: ["dict"],
    why: "딕셔너리 언패킹으로 합칠 때 같은 키는 뒤에 오는 값이 앞의 값을 덮어쓴다.",
    q: "print({**{\"a\": 1}, **{\"a\": 2}}) 의 출력 결과는?",
    a: "{'a': 2}",
  }),
  q.input({
    id: "py-0058",
    d: "advanced",
    tags: ["내장함수"],
    why: "파이썬 round는 정확히 .5일 때 가장 가까운 짝수로 반올림(banker's rounding)한다. round(2.5)는 2, round(3.5)는 4.",
    q: "print(round(2.5)) 의 출력 결과는?",
    a: "2",
  }),
  q.input({
    id: "py-0059",
    d: "intermediate",
    tags: ["tuple"],
    why: "괄호만으로는 튜플이 되지 않고 그냥 값을 묶는 괄호다. 원소 1개 튜플은 (1,)처럼 쉼표가 필요하다.",
    q: "print(type((1)).__name__) 의 출력 결과는?",
    a: "int",
  }),
  q.input({
    id: "py-0060",
    d: "intermediate",
    tags: ["정렬"],
    why: "문자열 기본 정렬은 유니코드 코드 포인트 순이라 대문자(A=65)가 소문자(a=97)보다 앞선다. 대소문자 무시는 key=str.lower.",
    q: "print(sorted([\"b\", \"A\", \"a\"])) 의 출력 결과는?",
    a: "['A', 'a', 'b']",
  }),
  q.input({
    id: "py-0061",
    d: "intermediate",
    tags: ["문자열", "포매팅"],
    why: "f-string의 :, 서식은 천 단위 구분 쉼표를 넣는다.",
    q: "print(f\"{1234567:,}\") 의 출력 결과는?",
    a: "1,234,567",
  }),
  q.input({
    id: "py-0062",
    d: "intermediate",
    tags: ["문자열", "포매팅"],
    why: ":.1% 서식은 값에 100을 곱하고 소수 첫째 자리까지 표시한 뒤 %를 붙인다.",
    q: "print(f\"{0.25:.1%}\") 의 출력 결과는?",
    a: "25.0%",
  }),
  q.input({
    id: "py-0063",
    d: "beginner",
    tags: ["문자열"],
    why: "구분자.join(리스트)는 리스트의 문자열 원소 사이에 구분자를 넣어 하나의 문자열로 만든다.",
    q: "print(\"-\".join([\"a\", \"b\", \"c\"])) 의 출력 결과는?",
    a: "a-b-c",
  }),
  q.input({
    id: "py-0064",
    d: "intermediate",
    tags: ["collections"],
    why: "Counter는 원소별 개수를 세고 most_common(n)은 가장 많은 n개를 (원소, 개수) 튜플 리스트로 돌려준다. banana에서 a는 3번.",
    q: "from collections import Counter\nprint(Counter(\"banana\").most_common(1))\n의 출력 결과는?",
    a: "[('a', 3)]",
  }),
  q.input({
    id: "py-0065",
    d: "intermediate",
    tags: ["언패킹"],
    why: "별표 언패킹 변수는 나머지 원소를 항상 리스트로 받는다.",
    q: "a, *b = [1, 2, 3]\nprint(b)\n의 출력 결과는?",
    a: "[2, 3]",
  }),
  q.input({
    id: "py-0066",
    d: "advanced",
    tags: ["generator"],
    why: "제너레이터는 한 번 끝까지 소비하면 다시 처음부터 돌지 않는다. 두 번째 list(g)는 빈 리스트다.",
    q: "g = (x for x in range(3))\nlist(g)\nprint(list(g))\n의 출력 결과는?",
    a: "[]",
  }),
  q.input({
    id: "py-0067",
    d: "advanced",
    tags: ["클로저"],
    why: "람다는 i의 값이 아니라 변수 i 자체를 참조하고, 호출 시점에 루프가 끝나 i=2다(late binding). lambda i=i: i 로 값을 고정할 수 있다.",
    q: "fs = [lambda: i for i in range(3)]\nprint(fs[0]())\n의 출력 결과는?",
    a: "2",
  }),
  q.input({
    id: "py-0068",
    d: "intermediate",
    tags: ["내장함수"],
    why: "int(문자열, 진법)은 해당 진법 문자열을 10진 정수로 변환한다. 2진수 10은 2.",
    q: "print(int(\"10\", 2)) 의 출력 결과는?",
    a: "2",
  }),
  q.input({
    id: "py-0069",
    d: "advanced",
    tags: ["내장함수"],
    why: "all은 '거짓인 원소가 하나도 없으면' True다. 빈 반복 가능 객체는 거짓 원소가 없으므로 True(공허한 참). any([])는 False.",
    q: "print(all([])) 의 출력 결과는?",
    a: "True",
  }),
  q.input({
    id: "py-0070",
    d: "intermediate",
    tags: ["list comprehension"],
    why: "for를 두 번 쓰면 앞 for가 바깥 루프다. x=1일 때 10, 20, x=2일 때 20, 40.",
    q: "print([x * y for x in [1, 2] for y in [10, 20]]) 의 출력 결과는?",
    a: "[10, 20, 20, 40]",
  }),
  q.input({
    id: "py-0071",
    d: "beginner",
    tags: ["set"],
    why: "set은 중복을 제거한다. hello의 고유 문자는 h, e, l, o 4개.",
    q: "print(len(set(\"hello\"))) 의 출력 결과는?",
    a: "4",
  }),
  q.input({
    id: "py-0072",
    d: "beginner",
    tags: ["dict"],
    why: "딕셔너리에 in을 쓰면 값이 아니라 키에 존재하는지 검사한다.",
    q: "print(\"a\" in {\"a\": 1}) 의 출력 결과는?",
    a: "True",
  }),
  q.input({
    id: "py-0073",
    d: "intermediate",
    tags: ["연산자"],
    why: "//는 몫을 버림이 아니라 음의 무한대 방향으로 내림(floor)한다. -3.5를 내림하면 -4.",
    q: "print(-7 // 2) 의 출력 결과는?",
    a: "-4",
  }),
  q.input({
    id: "py-0074",
    d: "intermediate",
    tags: ["연산자"],
    why: "거듭제곱 **은 오른쪽 결합이라 2 ** (3 ** 2) = 2 ** 9 = 512다.",
    q: "print(2 ** 3 ** 2) 의 출력 결과는?",
    a: "512",
  }),

  // ── 문법 빈칸 ──
  q.blank({
    id: "py-0075",
    d: "beginner",
    tags: ["반복문"],
    why: "enumerate는 (인덱스, 값) 쌍을 돌려주며 start로 시작 번호를 바꿀 수 있다.",
    code: "for i, item in {{b1}}(items, start=1):\n    print(i, item)",
    answers: ["enumerate"],
  }),
  q.blank({
    id: "py-0076",
    d: "beginner",
    tags: ["dict"],
    why: "dict.items()는 (키, 값) 쌍을 돌려줘 두 변수로 바로 언패킹할 수 있다.",
    code: "for key, value in scores.{{b1}}():\n    print(key, value)",
    answers: ["items"],
  }),
  q.blank({
    id: "py-0077",
    d: "beginner",
    tags: ["문자열", "포매팅"],
    why: "문자열 앞에 f를 붙이면 중괄호 안의 표현식이 값으로 치환되는 f-string이 된다.",
    code: "total = 3000\nprint({{b1}}\"합계: {total:,}원\")",
    answers: ["f"],
  }),
  q.blank({
    id: "py-0078",
    d: "intermediate",
    tags: ["모듈"],
    why: "스크립트로 직접 실행하면 __name__이 \"__main__\"이 되고, import되면 모듈 이름이 된다. import 시 실행을 막을 때 쓴다.",
    code: "if __name__ == \"{{b1}}\":\n    main()",
    answers: ["__main__"],
  }),
  q.blank({
    id: "py-0079",
    d: "intermediate",
    tags: ["generator"],
    why: "함수 안에 yield가 있으면 호출 시 값을 한 번에 하나씩 돌려주는 제너레이터 객체가 반환된다.",
    code: "def countdown(n):\n    while n > 0:\n        {{b1}} n\n        n -= 1",
    answers: ["yield"],
  }),
  q.blank({
    id: "py-0080",
    d: "beginner",
    tags: ["파일"],
    why: "\"w\"는 쓰기 모드로 기존 내용을 지우고 새로 쓴다. 이어 쓰려면 \"a\"(append)를 쓴다.",
    code: "# 파일을 새로 만들어 쓰기 (기존 내용 삭제)\nwith open(\"out.txt\", \"{{b1}}\", encoding=\"utf-8\") as f:\n    f.write(\"hello\")",
    answers: ["w"],
  }),
  q.blank({
    id: "py-0081",
    d: "intermediate",
    tags: ["정렬"],
    why: "sorted/sort의 key에는 비교 기준 값을 만드는 함수를 넘긴다.",
    code: "# 나이 오름차순 정렬\nusers_sorted = sorted(users, {{b1}}=lambda u: u[\"age\"])",
    answers: ["key"],
  }),

  // ── 개념 판단 ──
  q.mc({
    id: "py-0082",
    d: "intermediate",
    tags: ["연산자"],
    why: "==는 값이 같은지, is는 같은 객체인지 비교한다. None은 싱글턴이라 is None으로 비교하는 것이 관례다.",
    q: "변수 x가 None인지 검사하는 가장 권장되는 방법은?",
    options: ["x == None", "x is None", "x.equals(None)", "type(x) == None"],
    a: 1,
  }),
  q.mc({
    id: "py-0083",
    d: "intermediate",
    tags: ["예외처리"],
    why: "try-except-else에서 else는 try 블록이 예외 없이 끝났을 때만 실행된다. finally는 항상 실행된다.",
    q: "try/except/else/finally 구문에서 else 블록이 실행되는 시점은?",
    options: ["예외가 발생했을 때", "try 블록이 예외 없이 끝났을 때", "항상", "finally 이후"],
    a: 1,
  }),
  q.mc({
    id: "py-0084",
    d: "advanced",
    tags: ["OOP"],
    why: "@classmethod는 첫 인자로 클래스(cls)를 받아 대체 생성자 등에 쓰고, @staticmethod는 인스턴스·클래스 어느 것도 자동으로 받지 않는다.",
    q: "첫 번째 인자로 클래스 자체(cls)를 자동으로 전달받는 메서드 데코레이터는?",
    options: ["@staticmethod", "@classmethod", "@property", "@abstractmethod"],
    a: 1,
  }),
  q.t2d({
    id: "py-0085",
    d: "advanced",
    tags: ["OOP"],
    term: "__repr__",
    def: "개발자용으로 객체를 모호하지 않게 표현하는 문자열을 반환하는 메서드로, __str__이 없으면 print에도 대신 쓰인다",
  }),
  q.mc({
    id: "py-0086",
    d: "intermediate",
    tags: ["타입힌트"],
    why: "타입 힌트는 실행 시 강제되지 않는다. mypy 같은 정적 분석 도구나 IDE가 활용할 뿐이다.",
    q: "def f(x: int) -> str: 로 정의한 함수에 f(\"a\")를 호출하면?",
    options: [
      "TypeError가 즉시 발생한다",
      "타입 힌트는 실행 시 강제되지 않아 함수 본문대로 실행된다",
      "\"a\"가 자동으로 int로 변환된다",
      "문법 오류로 함수 정의가 실패한다",
    ],
    a: 1,
  }),
  q.d2t({
    id: "py-0087",
    d: "intermediate",
    tags: ["collections"],
    term: "defaultdict",
    def: "없는 키를 조회하면 지정한 팩토리 함수로 기본값을 만들어 넣어주는 collections의 딕셔너리",
  }),
  q.d2t({
    id: "py-0088",
    d: "advanced",
    tags: ["복사"],
    term: "copy.deepcopy",
    def: "중첩된 내부 객체까지 모두 재귀적으로 새로 만들어 원본과 완전히 독립된 사본을 만드는 함수",
  }),

  // ── Pandas ──
  q.input({
    id: "py-0089",
    d: "intermediate",
    tags: ["Pandas"],
    why: "loc은 라벨 기반이라 끝 라벨을 포함한다. 기본 정수 인덱스에서 loc[0:2]는 0, 1, 2의 3행, iloc[0:2]는 2행이다.",
    q: "기본 정수 인덱스(0부터)를 가진 DataFrame에서 df.loc[0:2]가 반환하는 행 수는?",
    a: "3",
  }),
  q.blank({
    id: "py-0090",
    d: "intermediate",
    tags: ["Pandas"],
    why: "pandas 불리언 인덱싱에서 조건 결합은 and/or 대신 비트 연산자 &, |를 쓰고 각 조건을 괄호로 감싸야 한다.",
    code: "# 30세 초과이면서 서울 거주\ndf[(df[\"age\"] > 30) {{b1}} (df[\"city\"] == \"Seoul\")]",
    answers: ["&"],
  }),
  q.mc({
    id: "py-0091",
    d: "intermediate",
    tags: ["Pandas"],
    why: "and는 Series 전체를 하나의 참/거짓으로 바꾸려 해 'truth value of a Series is ambiguous' 오류가 난다. 원소별 비교는 &를 쓴다.",
    q: "df[df.a > 1 and df.b < 5] 가 ValueError를 내는 이유는?",
    options: [
      "a, b 컬럼이 문자열이라서",
      "and가 Series 전체를 하나의 bool로 평가하려 하기 때문",
      "대괄호 안에는 조건을 하나만 쓸 수 있어서",
      "비교 연산자 앞뒤에 공백이 있어서",
    ],
    a: 1,
  }),
  q.blank({
    id: "py-0092",
    d: "beginner",
    tags: ["Pandas", "groupby"],
    why: "groupby 후 컬럼을 선택하고 mean()을 호출하면 그룹별 평균이 Series로 나온다.",
    code: "# 부서별 평균 급여\ndf.groupby(\"dept\")[\"salary\"].{{b1}}()",
    answers: ["mean"],
  }),
  q.blank({
    id: "py-0093",
    d: "intermediate",
    tags: ["Pandas", "groupby"],
    why: "named aggregation은 새컬럼=(원본컬럼, 집계함수) 형태로 결과 컬럼 이름까지 지정한다.",
    code: "# 부서별 매출 합계를 total 컬럼으로\ndf.groupby(\"dept\").agg(total=(\"sales\", \"{{b1}}\"))",
    answers: ["sum"],
  }),
  q.blank({
    id: "py-0094",
    d: "beginner",
    tags: ["Pandas", "merge"],
    why: "how=\"left\"는 왼쪽 DataFrame의 모든 행을 유지하고 매칭되지 않는 오른쪽 값은 NaN으로 채운다(SQL LEFT JOIN).",
    code: "# users의 모든 행 유지\npd.merge(users, orders, on=\"user_id\", how=\"{{b1}}\")",
    answers: ["left"],
  }),
  q.blank({
    id: "py-0095",
    d: "intermediate",
    tags: ["Pandas", "결측치"],
    why: "이상치가 있는 수치 컬럼은 평균보다 중앙값으로 결측치를 대체하는 편이 왜곡이 적다.",
    code: "# 결측치를 중앙값으로 대체\ndf[\"age\"] = df[\"age\"].fillna(df[\"age\"].{{b1}}())",
    answers: ["median"],
  }),
  q.blank({
    id: "py-0096",
    d: "beginner",
    tags: ["Pandas"],
    why: "sort_values는 기본 오름차순이다. ascending=False로 내림차순 정렬한다.",
    code: "# 매출 내림차순\ndf.sort_values(\"sales\", {{b1}}=False)",
    answers: ["ascending"],
  }),
  q.blank({
    id: "py-0097",
    d: "beginner",
    tags: ["Pandas"],
    why: "columns= 인자로 삭제할 컬럼 이름 목록을 넘기면 axis를 따로 지정하지 않아도 된다.",
    code: "df = df.drop({{b1}}=[\"tmp\", \"memo\"])",
    answers: ["columns"],
  }),
  q.blank({
    id: "py-0098",
    d: "beginner",
    tags: ["Pandas", "날짜"],
    why: "pd.to_datetime은 문자열 컬럼을 datetime64로 바꿔 .dt 접근자로 연·월·요일 등을 꺼낼 수 있게 한다.",
    code: "df[\"date\"] = pd.{{b1}}(df[\"date\"])",
    answers: ["to_datetime"],
  }),
  q.blank({
    id: "py-0099",
    d: "intermediate",
    tags: ["Pandas", "날짜"],
    why: "datetime 컬럼의 .dt.month는 1~12의 월 값을 돌려준다. .dt.dayofweek은 월요일=0인 요일 번호다.",
    code: "# 월(1~12) 추출\ndf[\"month\"] = df[\"date\"].dt.{{b1}}",
    answers: ["month"],
  }),
  q.blank({
    id: "py-0100",
    d: "beginner",
    tags: ["Pandas", "결측치"],
    why: "isna()가 결측 위치를 True로 표시하고, True=1로 합산하면 컬럼별 결측치 개수가 된다.",
    code: "# 컬럼별 결측치 개수\ndf.isna().{{b1}}()",
    answers: ["sum"],
  }),
  q.blank({
    id: "py-0101",
    d: "beginner",
    tags: ["Pandas", "dtype"],
    why: "astype은 컬럼의 자료형을 변환한다. 우편번호·ID처럼 계산하지 않는 숫자는 문자열로 두면 앞자리 0이 사라지지 않는다.",
    code: "df[\"zip_code\"] = df[\"zip_code\"].{{b1}}(str)",
    answers: ["astype"],
  }),
  q.blank({
    id: "py-0102",
    d: "intermediate",
    tags: ["Pandas"],
    why: "value_counts(normalize=True)는 개수 대신 전체 대비 비율을 돌려준다.",
    code: "# 카테고리별 비율\ndf[\"category\"].value_counts({{b1}}=True)",
    answers: ["normalize"],
  }),
  q.input({
    id: "py-0103",
    d: "intermediate",
    tags: ["Pandas", "결측치"],
    why: "pandas의 mean은 기본값 skipna=True라 NaN을 빼고 계산한다. (1 + 2) / 2 = 1.5.",
    q: "pd.Series([1, 2, None]).mean() 의 결과는?",
    a: "1.5",
  }),
  q.input({
    id: "py-0104",
    d: "intermediate",
    tags: ["NumPy", "결측치"],
    why: "NaN은 자기 자신과도 같지 않다. 결측 여부는 == 대신 isna()나 np.isnan()으로 검사한다.",
    q: "print(np.nan == np.nan) 의 출력 결과는?",
    a: "False",
  }),
  q.mc({
    id: "py-0105",
    d: "advanced",
    tags: ["Pandas"],
    why: "pandas 연산은 위치가 아니라 인덱스 라벨로 정렬(alignment)된 뒤 계산된다. 한쪽에만 있는 라벨은 NaN이 된다.",
    q: "인덱스가 [0, 1, 2]인 Series와 [1, 2, 3]인 Series를 더하면?",
    options: [
      "위치 순서대로 더해 3개 값이 나온다",
      "인덱스 라벨을 맞춰 더하므로 0과 3 라벨은 NaN이 된다",
      "인덱스가 달라 오류가 난다",
      "짧은 쪽에 맞춰 2개만 나온다",
    ],
    a: 1,
  }),
  q.mc({
    id: "py-0106",
    d: "advanced",
    tags: ["Pandas"],
    why: "df[조건][\"col\"] = 값은 사본에 대입될 수 있어 원본이 바뀌지 않을 수 있다(SettingWithCopyWarning). df.loc[조건, \"col\"] = 값으로 한 번에 지정한다.",
    q: "조건에 맞는 행의 특정 컬럼 값을 원본 DataFrame에서 안전하게 바꾸는 코드는?",
    options: [
      "df[df.age > 30][\"grade\"] = \"A\"",
      "df.loc[df.age > 30, \"grade\"] = \"A\"",
      "df.grade[df.age > 30].copy() = \"A\"",
      "df.iloc[df.age > 30][\"grade\"] = \"A\"",
    ],
    a: 1,
  }),
  q.mc({
    id: "py-0107",
    d: "intermediate",
    tags: ["Pandas"],
    why: "pd.cut은 값의 범위를 같은 너비로 나누고, pd.qcut은 분위수 기준으로 나눠 구간별 데이터 개수를 비슷하게 맞춘다.",
    q: "각 구간에 들어가는 데이터 개수가 비슷하도록 분위수 기준으로 구간을 나누는 함수는?",
    options: ["pd.cut", "pd.qcut", "pd.melt", "pd.crosstab"],
    a: 1,
  }),
  q.d2t({
    id: "py-0108",
    d: "intermediate",
    tags: ["Pandas"],
    term: "melt",
    def: "여러 컬럼에 펼쳐진 값을 (변수명, 값) 두 컬럼으로 모아 와이드 포맷을 롱 포맷으로 바꾸는 pandas 함수",
  }),
  q.mc({
    id: "py-0109",
    d: "advanced",
    tags: ["Pandas"],
    why: "pivot은 집계 없이 모양만 바꾸므로 같은 (index, columns) 조합이 중복되면 오류가 난다. pivot_table은 aggfunc로 중복을 집계한다.",
    q: "같은 (날짜, 상품) 조합이 여러 행 있을 때 df.pivot(...)이 오류를 내는 이유는?",
    options: [
      "pivot은 문자열 컬럼을 지원하지 않아서",
      "pivot은 집계하지 않아 중복 조합을 한 칸에 담을 수 없어서",
      "pivot은 인덱스를 두 개 이상 받아야 해서",
      "pivot은 날짜 컬럼을 쓸 수 없어서",
    ],
    a: 1,
  }),
  q.mc({
    id: "py-0110",
    d: "advanced",
    tags: ["Pandas", "groupby"],
    why: "transform은 그룹별 계산 결과를 원래 행 수에 맞춰 돌려줘 새 컬럼으로 바로 붙일 수 있다. agg는 그룹당 1행으로 줄어든다.",
    q: "각 행에 소속 그룹의 평균을 새 컬럼으로 붙이려 할 때 원래 행 수를 유지해 주는 메서드는?",
    options: ["groupby().agg(\"mean\")", "groupby().transform(\"mean\")", "groupby().size()", "groupby().first()"],
    a: 1,
  }),
  q.d2t({
    id: "py-0111",
    d: "intermediate",
    tags: ["Pandas", "중복"],
    term: "drop_duplicates",
    def: "지정한 컬럼 기준으로 중복된 행을 제거하고 keep 인자로 첫 번째 또는 마지막 행을 남기는 pandas 메서드",
  }),
  q.essay({
    id: "py-0112",
    d: "advanced",
    tags: ["Pandas", "성능"],
    q: "pandas에서 행 단위 for 루프나 apply보다 벡터화 연산이 빠른 이유를 한 문장으로 설명하시오.",
    a: "벡터화 연산은 파이썬 인터프리터 루프 대신 C로 구현된 NumPy 연산으로 배열 전체를 한 번에 처리하기 때문이다.",
  }),
];
