// SQL 확장: 실제 쿼리 작성/결과 예측/흔한 함정 위주. 키워드 정답은 모두 대문자로 통일한다.
import { themed } from "@/db/seed/defaultQuestions/builders";

const q = themed("SQL", ["SQL"]);

export const sqlExtraQuestions = [
  // ── 윈도우 함수 ──
  q.blank({
    id: "sql-0052",
    d: "intermediate",
    tags: ["윈도우함수"],
    why: "RANK는 동점에 같은 순위를 주고 그 다음 순위를 동점자 수만큼 건너뛴다(1,1,3). DENSE_RANK는 건너뛰지 않는다(1,1,2).",
    code: "-- 동점은 같은 순위, 다음 순위는 건너뜀 (1, 1, 3)\nSELECT name, {{b1}}() OVER (ORDER BY score DESC) AS rnk\nFROM exam;",
    answers: ["RANK"],
  }),
  q.blank({
    id: "sql-0053",
    d: "intermediate",
    tags: ["윈도우함수"],
    why: "DENSE_RANK는 동점 이후에도 순위를 연속으로 매긴다(1,1,2). N번째로 높은 값을 찾을 때 자주 쓴다.",
    code: "-- 동점은 같은 순위, 다음 순위는 연속 (1, 1, 2)\nSELECT name, {{b1}}() OVER (ORDER BY score DESC) AS rnk\nFROM exam;",
    answers: ["DENSE_RANK"],
  }),
  q.blank({
    id: "sql-0054",
    d: "advanced",
    tags: ["윈도우함수"],
    why: "LAG는 같은 파티션에서 현재 행보다 앞선 행의 값을, LEAD는 뒤 행의 값을 가져온다. 전일 대비 증감 계산에 쓴다.",
    code: "-- 사용자별 직전 결제 금액\nSELECT user_id, paid_at, amount,\n       {{b1}}(amount, 1) OVER (PARTITION BY user_id ORDER BY paid_at) AS prev_amount\nFROM payments;",
    answers: ["LAG"],
  }),
  q.blank({
    id: "sql-0055",
    d: "intermediate",
    tags: ["윈도우함수"],
    why: "PARTITION BY는 윈도우 계산을 그룹별로 나누지만 GROUP BY와 달리 행 수를 줄이지 않는다.",
    code: "-- 사용자별 누적 결제 금액\nSELECT user_id, paid_at,\n       SUM(amount) OVER ({{b1}} user_id ORDER BY paid_at) AS cum_amount\nFROM payments;",
    answers: ["PARTITION BY"],
  }),
  q.blank({
    id: "sql-0056",
    d: "advanced",
    tags: ["윈도우함수"],
    why: "ROWS BETWEEN 6 PRECEDING AND CURRENT ROW는 현재 행 포함 직전 7개 행을 윈도우로 잡아 7일 이동평균을 만든다.",
    code: "-- 7일 이동평균 (일별 1행 가정)\nSELECT dt,\n       AVG(sales) OVER (ORDER BY dt ROWS BETWEEN 6 {{b1}} AND CURRENT ROW) AS ma7\nFROM daily_sales;",
    answers: ["PRECEDING"],
  }),
  q.blank({
    id: "sql-0057",
    d: "advanced",
    tags: ["윈도우함수"],
    why: "NTILE(n)은 정렬된 행을 n개 그룹으로 최대한 균등하게 나눠 그룹 번호를 매긴다. 사분위·십분위 세그먼트에 쓴다.",
    code: "-- 점수 기준 4개 구간(사분위) 번호\nSELECT name, {{b1}}(4) OVER (ORDER BY score) AS quartile\nFROM exam;",
    answers: ["NTILE"],
  }),
  q.input({
    id: "sql-0058",
    d: "intermediate",
    tags: ["윈도우함수"],
    why: "RANK는 100(1위), 90(2위), 90(2위) 다음 순위를 건너뛰어 80이 4위가 된다.",
    q: "점수가 100, 90, 90, 80일 때 RANK() OVER (ORDER BY score DESC) 기준 80점의 순위는? (숫자만)",
    a: "4",
  }),
  q.mc({
    id: "sql-0059",
    d: "intermediate",
    tags: ["윈도우함수"],
    why: "GROUP BY는 부서별 1행으로 줄어들지만 윈도우 함수는 원래 행을 유지한 채 부서 평균을 각 행에 붙일 수 있다.",
    q: "직원별 행을 그대로 유지하면서 각 행 옆에 소속 부서의 평균 급여를 붙이려면?",
    options: [
      "SELECT dept, AVG(salary) FROM emp GROUP BY dept",
      "SELECT name, AVG(salary) OVER (PARTITION BY dept) FROM emp",
      "SELECT name, AVG(salary) FROM emp",
      "SELECT name, salary FROM emp HAVING AVG(salary)",
    ],
    a: 1,
  }),

  // ── 문법/작성 ──
  q.blank({
    id: "sql-0060",
    d: "beginner",
    tags: ["CASE"],
    why: "CASE 식은 CASE WHEN 조건 THEN 값 ... ELSE 값 END 형태로 쓰며 END를 빠뜨리면 문법 오류가 난다.",
    code: "SELECT id,\n       {{b1}} WHEN score >= 60 THEN 'pass' ELSE 'fail' {{b2}} AS result\nFROM exam;",
    answers: ["CASE", "END"],
  }),
  q.blank({
    id: "sql-0061",
    d: "intermediate",
    tags: ["JOIN", "NULL"],
    why: "LEFT JOIN 후 오른쪽 키가 NULL인 행만 남기면 '매칭되는 행이 없는' 대상(안티 조인)을 찾을 수 있다.",
    code: "-- 주문이 한 번도 없는 사용자\nSELECT u.id\nFROM users u\nLEFT JOIN orders o ON u.id = o.user_id\nWHERE o.user_id {{b1}};",
    answers: ["IS NULL"],
  }),
  q.blank({
    id: "sql-0062",
    d: "beginner",
    tags: ["집계"],
    why: "COUNT(DISTINCT col)은 중복을 제거한 고유 값 개수를 센다. 로그 테이블에서 순 사용자 수(UV)를 구할 때 쓴다.",
    code: "-- 로그인한 고유 사용자 수\nSELECT COUNT({{b1}} user_id) FROM logins;",
    answers: ["DISTINCT"],
  }),
  q.blank({
    id: "sql-0063",
    d: "beginner",
    tags: ["DDL"],
    why: "기존 테이블에 컬럼을 추가할 때는 ALTER TABLE ... ADD COLUMN을 쓴다.",
    code: "ALTER TABLE users {{b1}} COLUMN email VARCHAR(255);",
    answers: ["ADD"],
  }),
  q.blank({
    id: "sql-0064",
    d: "beginner",
    tags: ["인덱스", "DDL"],
    why: "CREATE INDEX 인덱스명 ON 테이블(컬럼) 형태로 인덱스를 만든다.",
    code: "CREATE {{b1}} idx_users_email ON users (email);",
    answers: ["INDEX"],
  }),
  q.blank({
    id: "sql-0065",
    d: "intermediate",
    tags: ["트랜잭션"],
    why: "COMMIT은 트랜잭션의 변경을 영구 반영한다. 두 UPDATE를 한 트랜잭션으로 묶어야 송금 중간 실패 시 한쪽만 반영되는 일을 막는다.",
    code: "BEGIN;\nUPDATE accounts SET balance = balance - 100 WHERE id = 1;\nUPDATE accounts SET balance = balance + 100 WHERE id = 2;\n{{b1}}; -- 변경 확정",
    answers: ["COMMIT"],
  }),
  q.blank({
    id: "sql-0066",
    d: "intermediate",
    tags: ["페이지네이션"],
    why: "LIMIT 10 OFFSET 20은 앞의 20행을 건너뛰고 21번째 행부터 10개를 가져온다. OFFSET이 커질수록 건너뛸 행도 모두 읽어 느려진다.",
    code: "-- 21번째 행부터 10개 (3페이지)\nSELECT * FROM orders ORDER BY created_at DESC LIMIT 10 {{b1}} 20;",
    answers: ["OFFSET"],
  }),
  q.blank({
    id: "sql-0067",
    d: "intermediate",
    tags: ["집합연산"],
    why: "INTERSECT는 두 SELECT 결과의 교집합을 반환한다.",
    code: "-- 1월과 2월에 모두 구매한 사용자\nSELECT user_id FROM jan_orders\n{{b1}}\nSELECT user_id FROM feb_orders;",
    answers: ["INTERSECT"],
  }),
  q.blank({
    id: "sql-0068",
    d: "intermediate",
    tags: ["집합연산"],
    why: "표준 SQL의 EXCEPT는 첫 결과에서 두 번째 결과에 있는 행을 뺀 차집합이다. Oracle에서는 MINUS를 쓴다.",
    code: "-- 1월엔 구매했지만 2월엔 구매하지 않은 사용자 (표준 SQL)\nSELECT user_id FROM jan_orders\n{{b1}}\nSELECT user_id FROM feb_orders;",
    answers: ["EXCEPT"],
  }),
  q.blank({
    id: "sql-0069",
    d: "beginner",
    tags: ["WHERE"],
    why: "IN은 여러 값 중 하나와 일치하는지 검사하며 OR 조건을 여러 번 쓰는 것과 같다.",
    code: "SELECT * FROM orders WHERE status {{b1}} ('paid', 'shipped');",
    answers: ["IN"],
  }),
  q.blank({
    id: "sql-0070",
    d: "beginner",
    tags: ["JOIN"],
    why: "CROSS JOIN은 조인 조건 없이 두 테이블의 모든 행 조합(카테시안 곱)을 만든다. 날짜×상품 뼈대 테이블을 만들 때 쓴다.",
    code: "-- 모든 날짜 × 모든 상품 조합 만들기\nSELECT d.dt, p.id\nFROM dates d\n{{b1}} JOIN products p;",
    answers: ["CROSS"],
  }),
  q.blank({
    id: "sql-0071",
    d: "intermediate",
    tags: ["NULL"],
    why: "NULLIF(a, b)는 a와 b가 같으면 NULL을 반환한다. 분모가 0이면 NULL이 되어 0으로 나누기 오류 대신 NULL 결과가 나온다.",
    code: "-- 노출이 0이면 오류 대신 NULL\nSELECT clicks * 1.0 / {{b1}}(impressions, 0) AS ctr FROM ads;",
    answers: ["NULLIF"],
  }),
  q.blank({
    id: "sql-0072",
    d: "advanced",
    tags: ["CTE"],
    why: "WITH RECURSIVE는 자기 자신을 참조하는 CTE로, 조직도·카테고리 트리 같은 계층 구조를 펼칠 때 쓴다.",
    code: "WITH {{b1}} org AS (\n  SELECT id, manager_id FROM emp WHERE manager_id IS NULL\n  UNION ALL\n  SELECT e.id, e.manager_id FROM emp e JOIN org o ON e.manager_id = o.id\n)\nSELECT * FROM org;",
    answers: ["RECURSIVE"],
  }),
  q.blank({
    id: "sql-0073",
    d: "intermediate",
    tags: ["날짜"],
    why: "PostgreSQL의 DATE_TRUNC('month', ts)는 타임스탬프를 해당 월의 첫 시각으로 잘라 월별 집계 키로 쓸 수 있게 한다.",
    code: "-- 월별 주문 수 (PostgreSQL)\nSELECT {{b1}}('month', created_at) AS month, COUNT(*)\nFROM orders\nGROUP BY 1;",
    answers: ["DATE_TRUNC"],
  }),

  // ── 결과 예측 ──
  q.input({
    id: "sql-0074",
    d: "beginner",
    tags: ["NULL", "집계"],
    why: "COUNT(컬럼)은 NULL을 세지 않는다. 1과 3만 세어 2가 된다.",
    q: "테이블 t의 컬럼 x 값이 1, NULL, 3일 때 SELECT COUNT(x) FROM t; 의 결과는?",
    a: "2",
  }),
  q.input({
    id: "sql-0075",
    d: "intermediate",
    tags: ["NULL", "집계"],
    why: "AVG는 NULL을 분모에서도 제외한다. (1+3)/2 = 2이며, NULL을 0으로 보고 싶다면 AVG(COALESCE(x, 0))을 써야 한다.",
    q: "테이블 t의 컬럼 x 값이 1, NULL, 3일 때 SELECT AVG(x) FROM t; 의 결과는? (정수로)",
    a: "2",
  }),
  q.input({
    id: "sql-0076",
    d: "intermediate",
    tags: ["NULL", "집계"],
    why: "집계 대상 값이 모두 NULL이면 SUM은 0이 아니라 NULL을 반환한다. 0이 필요하면 COALESCE(SUM(x), 0)으로 감싼다.",
    q: "x 값이 모두 NULL인 테이블에서 SELECT SUM(x) 의 결과는? (대문자로)",
    a: "NULL",
  }),
  q.input({
    id: "sql-0077",
    d: "advanced",
    tags: ["NULL"],
    why: "x NOT IN (1, NULL)은 x <> 1 AND x <> NULL로 풀리는데 x <> NULL이 UNKNOWN이라 어떤 행도 참이 되지 않아 결과는 0행이다. NOT EXISTS를 쓰면 안전하다.",
    q: "x 값이 1, 2, 3인 테이블에서 SELECT * FROM t WHERE x NOT IN (1, NULL); 이 반환하는 행 수는?",
    a: "0",
  }),
  q.input({
    id: "sql-0078",
    d: "beginner",
    tags: ["NULL"],
    why: "NULL은 비교 대상이 아니라 '알 수 없음'이므로 x > 1에서 NULL 행은 참이 아니다. 3만 남는다.",
    q: "x 값이 1, NULL, 3일 때 SELECT COUNT(*) FROM t WHERE x > 1; 의 결과는?",
    a: "1",
  }),
  q.input({
    id: "sql-0079",
    d: "intermediate",
    tags: ["JOIN"],
    why: "사용자1은 주문 2건과 매칭돼 2행, 사용자2는 1행, 주문이 없는 사용자3도 LEFT JOIN이라 NULL로 1행 → 총 4행.",
    q: "users 3명 중 1번은 주문 2건, 2번은 1건, 3번은 0건이다. users LEFT JOIN orders의 결과 행 수는?",
    a: "4",
  }),
  q.input({
    id: "sql-0080",
    d: "beginner",
    tags: ["JOIN"],
    why: "INNER JOIN은 매칭되는 행만 남는다. 사용자1의 2행 + 사용자2의 1행 = 3행. 주문 없는 사용자3은 빠진다.",
    q: "users 3명 중 1번은 주문 2건, 2번은 1건, 3번은 0건이다. users INNER JOIN orders의 결과 행 수는?",
    a: "3",
  }),
  q.input({
    id: "sql-0081",
    d: "beginner",
    tags: ["JOIN"],
    why: "CROSS JOIN은 모든 조합을 만들므로 행 수는 3 × 4 = 12다.",
    q: "3행 테이블과 4행 테이블을 CROSS JOIN한 결과 행 수는?",
    a: "12",
  }),
  q.input({
    id: "sql-0082",
    d: "intermediate",
    tags: ["집합연산"],
    why: "UNION ALL은 중복을 제거하지 않아 3행 + 2행 = 5행. UNION이었다면 {1,2,3}으로 3행이 된다.",
    q: "SELECT 결과 (1, 2, 2)와 (2, 3)을 UNION ALL로 합친 결과 행 수는?",
    a: "5",
  }),
  q.input({
    id: "sql-0083",
    d: "intermediate",
    tags: ["연산"],
    why: "PostgreSQL에서 정수끼리 나누면 소수점 이하를 버린 정수 나눗셈이 되어 7 / 2 = 3이다. 비율 계산 시 7 * 1.0 / 2처럼 형변환이 필요하다.",
    q: "PostgreSQL에서 SELECT 7 / 2; 의 결과는?",
    a: "3",
  }),

  // ── 판단/함정 ──
  q.mc({
    id: "sql-0084",
    d: "intermediate",
    tags: ["실행순서"],
    why: "논리적 처리 순서는 FROM → WHERE → GROUP BY → HAVING → SELECT → ORDER BY다. WHERE 시점에는 SELECT 별칭이 아직 없다.",
    q: "SELECT price * qty AS total ... WHERE total > 100 이 오류가 나는 이유는?",
    options: [
      "별칭에는 숫자 비교를 쓸 수 없어서",
      "WHERE가 SELECT보다 먼저 처리되어 별칭이 아직 정의되지 않아서",
      "AS 키워드를 생략해야 해서",
      "곱셈 결과는 WHERE에서 비교할 수 없어서",
    ],
    a: 1,
  }),
  q.mc({
    id: "sql-0085",
    d: "intermediate",
    tags: ["실행순서"],
    why: "ORDER BY는 SELECT 이후에 처리되므로 SELECT 별칭을 사용할 수 있다.",
    q: "SELECT 절에서 만든 별칭을 표준적으로 참조할 수 있는 절은?",
    options: ["WHERE", "GROUP BY", "HAVING", "ORDER BY"],
    a: 3,
  }),
  q.mc({
    id: "sql-0086",
    d: "intermediate",
    tags: ["GROUP BY"],
    why: "GROUP BY에 없는 비집계 컬럼(name)을 SELECT하면 그룹 안에서 어떤 값을 보여줄지 정할 수 없어 표준 SQL에서 오류가 난다.",
    q: "표준 SQL에서 오류가 나는 쿼리는?",
    options: [
      "SELECT dept, COUNT(*) FROM emp GROUP BY dept",
      "SELECT dept, name, COUNT(*) FROM emp GROUP BY dept",
      "SELECT dept, MAX(salary) FROM emp GROUP BY dept",
      "SELECT COUNT(*) FROM emp",
    ],
    a: 1,
  }),
  q.mc({
    id: "sql-0087",
    d: "beginner",
    tags: ["집계"],
    why: "COUNT(1)의 1은 NULL이 될 수 없는 상수라 모든 행을 센다. COUNT(*)와 결과가 같다.",
    q: "COUNT(1)과 COUNT(*)의 결과를 비교하면?",
    options: ["항상 같다", "COUNT(1)이 NULL 행을 제외한다", "COUNT(1)은 첫 번째 컬럼만 센다", "COUNT(*)가 항상 1 크다"],
    a: 0,
  }),
  q.mc({
    id: "sql-0088",
    d: "advanced",
    tags: ["JOIN"],
    why: "WHERE o.status = 'paid'는 오른쪽이 NULL인 행을 모두 걸러내 LEFT JOIN이 사실상 INNER JOIN이 된다. 조건을 ON 절로 옮겨야 주문 없는 사용자가 유지된다.",
    q: "users LEFT JOIN orders o ON ... WHERE o.status = 'paid' 를 실행했더니 주문 없는 사용자가 사라졌다. 원인은?",
    options: [
      "LEFT JOIN은 원래 주문 없는 행을 제거한다",
      "WHERE 조건이 오른쪽 NULL 행을 걸러내 INNER JOIN처럼 동작했다",
      "status 컬럼에 인덱스가 없어서",
      "ON 절에 조건이 두 개 이상이라서",
    ],
    a: 1,
  }),
  q.mc({
    id: "sql-0089",
    d: "advanced",
    tags: ["JOIN", "집계"],
    why: "orders(1) : order_items(N)을 조인하면 주문 행이 품목 수만큼 복제된다. 그 상태에서 orders.amount를 SUM하면 중복 합산(fan-out)된다.",
    q: "orders와 order_items를 조인한 뒤 SUM(orders.amount)를 구했더니 실제 매출보다 크게 나왔다. 가장 유력한 원인은?",
    options: [
      "SUM 함수가 NULL을 0으로 계산해서",
      "1:N 조인으로 주문 행이 품목 수만큼 복제되어 중복 합산됐다",
      "amount 컬럼이 정수형이라서",
      "ORDER BY를 쓰지 않아서",
    ],
    a: 1,
  }),
  q.mc({
    id: "sql-0090",
    d: "intermediate",
    tags: ["날짜"],
    why: "timestamp 컬럼에 BETWEEN '2024-01-01' AND '2024-01-31'을 쓰면 31일 00:00:00까지만 포함된다. 반열린 구간 >= 시작 AND < 다음날이 안전하다.",
    q: "timestamp 컬럼으로 2024년 1월 전체 주문을 누락 없이 조회하는 조건은?",
    options: [
      "created_at BETWEEN '2024-01-01' AND '2024-01-31'",
      "created_at >= '2024-01-01' AND created_at < '2024-02-01'",
      "created_at = '2024-01'",
      "created_at LIKE '2024-01-%'",
    ],
    a: 1,
  }),
  q.mc({
    id: "sql-0091",
    d: "intermediate",
    tags: ["중복"],
    why: "그룹별 행 수가 2 이상인 값이 중복이다. 집계 결과를 조건으로 거르므로 HAVING을 쓴다.",
    q: "users 테이블에서 중복 등록된 email을 찾는 쿼리는?",
    options: [
      "SELECT email FROM users WHERE COUNT(*) > 1",
      "SELECT DISTINCT email FROM users",
      "SELECT email FROM users GROUP BY email HAVING COUNT(*) > 1",
      "SELECT email FROM users ORDER BY email",
    ],
    a: 2,
  }),
  q.mc({
    id: "sql-0092",
    d: "intermediate",
    tags: ["집합연산"],
    why: "UNION/UNION ALL은 두 SELECT의 컬럼 개수가 같고 대응 컬럼의 타입이 호환되어야 한다. 컬럼 이름은 달라도 된다.",
    q: "UNION으로 두 SELECT를 합칠 때 반드시 맞아야 하는 것은?",
    options: ["컬럼 이름", "컬럼 개수와 호환되는 타입", "테이블 이름", "행 개수"],
    a: 1,
  }),

  // ── 인덱스/성능 ──
  q.mc({
    id: "sql-0093",
    d: "advanced",
    tags: ["인덱스"],
    why: "복합 인덱스 (a, b)는 a로 먼저 정렬된 구조라 선두 컬럼 a 조건 없이 b만으로는 인덱스 탐색 범위를 좁히기 어렵다(leftmost prefix 원칙).",
    q: "복합 인덱스 (a, b)가 있을 때 인덱스를 가장 효율적으로 활용하기 어려운 조건은?",
    options: ["WHERE a = 1", "WHERE a = 1 AND b = 2", "WHERE b = 2", "WHERE a = 1 AND b > 2"],
    a: 2,
  }),
  q.mc({
    id: "sql-0094",
    d: "advanced",
    tags: ["인덱스"],
    why: "인덱스 컬럼에 함수를 씌우면 인덱스에 저장된 원래 값 순서를 쓸 수 없다. 범위 조건(>= '2024-01-01' AND < '2025-01-01')으로 바꾸는 것이 좋다.",
    q: "created_at에 인덱스가 있는데 WHERE YEAR(created_at) = 2024 가 느린 이유는?",
    options: [
      "YEAR 함수는 NULL을 반환해서",
      "인덱스 컬럼을 함수로 가공해 인덱스를 그대로 활용할 수 없어서",
      "2024는 문자열로 써야 해서",
      "WHERE에는 날짜 비교를 쓸 수 없어서",
    ],
    a: 1,
  }),
  q.d2t({
    id: "sql-0095",
    d: "advanced",
    tags: ["인덱스"],
    term: "커버링 인덱스",
    def: "쿼리에 필요한 모든 컬럼이 인덱스에 포함되어 테이블 본문을 읽지 않고 인덱스만으로 결과를 만들 수 있는 인덱스",
  }),
  q.t2d({
    id: "sql-0096",
    d: "advanced",
    tags: ["인덱스"],
    term: "클러스터드 인덱스",
    def: "인덱스 키 순서대로 테이블 데이터 자체가 물리적으로 정렬·저장되는 인덱스로, 테이블당 하나만 존재한다",
  }),
  q.d2t({
    id: "sql-0097",
    d: "intermediate",
    tags: ["인덱스"],
    term: "카디널리티",
    def: "컬럼에 들어 있는 고유 값의 개수 정도로, 높을수록 인덱스로 걸러낼 수 있는 선택도가 좋다",
  }),
  q.d2t({
    id: "sql-0098",
    d: "advanced",
    tags: ["뷰"],
    term: "머티리얼라이즈드 뷰",
    def: "쿼리 결과를 실제로 저장해 두고 주기적으로 갱신하는 뷰로, 조회는 빠르지만 원본과 시차가 생길 수 있다",
  }),

  // ── 트랜잭션 격리 ──
  q.mc({
    id: "sql-0099",
    d: "advanced",
    tags: ["트랜잭션", "격리수준"],
    why: "READ UNCOMMITTED는 다른 트랜잭션이 커밋하지 않은 변경까지 읽을 수 있어 Dirty Read가 발생한다.",
    q: "커밋되지 않은 다른 트랜잭션의 변경 내용을 읽는 Dirty Read가 허용되는 격리 수준은?",
    options: ["READ UNCOMMITTED", "READ COMMITTED", "REPEATABLE READ", "SERIALIZABLE"],
    a: 0,
  }),
  q.t2d({
    id: "sql-0100",
    d: "advanced",
    tags: ["트랜잭션", "격리수준"],
    term: "Non-Repeatable Read",
    def: "한 트랜잭션에서 같은 행을 두 번 읽는 사이 다른 트랜잭션이 그 행을 수정·커밋해 두 결과가 달라지는 현상",
  }),
  q.d2t({
    id: "sql-0101",
    d: "advanced",
    tags: ["트랜잭션", "격리수준"],
    term: "Phantom Read",
    def: "같은 범위 조건으로 두 번 조회하는 사이 다른 트랜잭션이 행을 삽입해 처음에 없던 행이 나타나는 현상",
  }),
  q.d2t({
    id: "sql-0102",
    d: "intermediate",
    tags: ["트랜잭션"],
    term: "SAVEPOINT",
    def: "트랜잭션 중간에 복귀 지점을 만들어 전체가 아닌 그 지점 이후 작업만 롤백할 수 있게 하는 명령",
  }),

  // ── 보안/권한 ──
  q.mc({
    id: "sql-0103",
    d: "intermediate",
    tags: ["보안"],
    why: "Prepared Statement는 SQL 구조와 값을 분리해 전달하므로 입력값이 SQL 문법으로 해석되지 않는다.",
    q: "SQL 인젝션을 막는 가장 근본적인 방법은?",
    options: [
      "사용자 입력을 문자열로 이어 붙여 쿼리를 만든다",
      "Prepared Statement(바인딩 변수)로 값을 전달한다",
      "쿼리를 대문자로만 작성한다",
      "SELECT *를 사용하지 않는다",
    ],
    a: 1,
  }),
  q.t2d({
    id: "sql-0104",
    d: "intermediate",
    tags: ["DCL"],
    term: "DCL",
    def: "GRANT, REVOKE처럼 사용자에게 데이터베이스 객체에 대한 권한을 부여하거나 회수하는 SQL 명령어 집합",
  }),

  // ── 서술 ──
  q.essay({
    id: "sql-0105",
    d: "intermediate",
    tags: ["JOIN"],
    q: "LEFT JOIN 후 결과 행 수가 왼쪽 테이블보다 많아질 수 있는 이유를 한 문장으로 설명하시오.",
    a: "오른쪽 테이블에 조인 키가 일치하는 행이 여러 개 있으면 왼쪽 행이 그 개수만큼 복제되기 때문이다.",
  }),
  q.essay({
    id: "sql-0106",
    d: "intermediate",
    tags: ["성능"],
    q: "운영 쿼리에서 SELECT * 사용을 피하는 이유를 한 문장으로 설명하시오.",
    a: "필요 없는 컬럼까지 읽어 I/O와 전송 비용이 늘고 스키마가 바뀌면 결과 구조도 바뀌어 코드가 깨질 수 있기 때문이다.",
  }),
  q.essay({
    id: "sql-0107",
    d: "advanced",
    tags: ["NULL"],
    q: "NOT IN 대신 NOT EXISTS를 권장하는 이유를 한 문장으로 설명하시오.",
    a: "서브쿼리 결과에 NULL이 하나라도 있으면 NOT IN은 모든 비교가 UNKNOWN이 되어 결과가 비지만 NOT EXISTS는 NULL의 영향을 받지 않기 때문이다.",
  }),
];
